// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PlayAPISDK.Catalog.Steam.Chart;
using PlayAPISDK.Catalog.Steam.ConcurrentUsers;
using PlayAPISDK.Catalog.Steam.Pricing;
using PlayAPISDK.Catalog.Steam.Reviews;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PlayAPISDK.Catalog.Steam
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\steam
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SteamRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chart property</summary>
        public global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder Chart
        {
            get => new global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The concurrentUsers property</summary>
        public global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.ConcurrentUsersRequestBuilder ConcurrentUsers
        {
            get => new global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.ConcurrentUsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pricing property</summary>
        public global::PlayAPISDK.Catalog.Steam.Pricing.PricingRequestBuilder Pricing
        {
            get => new global::PlayAPISDK.Catalog.Steam.Pricing.PricingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reviews property</summary>
        public global::PlayAPISDK.Catalog.Steam.Reviews.ReviewsRequestBuilder Reviews
        {
            get => new global::PlayAPISDK.Catalog.Steam.Reviews.ReviewsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Steam.SteamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SteamRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/steam", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Steam.SteamRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SteamRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/steam", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
