name: "igdb_transform"
version: "1.0.0"
config-version: 2
profile: "dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
    - "target"
    - "dbt_packages"

vars:
    threads: 8

models:
    igdb_transform:
        +persist_docs:
            relation: true
            columns: true
        staging:
            +materialized: view
            +schema: staging
        intermediate:
            +materialized: view
            +schema: intermediate
        marts:
            +materialized: table
            +incremental_strategy: merge
            +schema: igdb
            bridges:
                +schema: igdb
