catalog:
    outputs:
        dev:
            dbname: catalogdev
            host: localhost
            pass: pudGW.E7_u8eF8Qhnym)E0
            port: 5433
            schema: dbt_dev
            threads: 2
            type: postgres
            user: postgres
    target: dev
dbt:
    outputs:
        dev:
            dbname: catalogdev
            host: localhost
            pass: pudGW.E7_u8eF8Qhnym)E0
            port: 5433
            schema: public
            threads: 2
            type: postgres
            user: postgres
    target: dev
