import type { IconType } from "react-icons";
import { BsNintendoSwitch } from "react-icons/bs";
import {
    FaApple,
    FaBattleNet,
    FaGamepad,
    FaGithub,
    FaItchIo,
    FaLinux,
    FaPlaystation,
    FaShoppingCart,
    FaSteam,
    FaWindows,
    FaXbox,
    FaYoutube,
    FaWikipediaW,
    FaUnity,
    FaGlobe,
    FaTwitch,
    FaDiscord,
    FaAndroid,
    FaAppStoreIos,
    FaTwitter,
} from "react-icons/fa";
import {
    SiCryengine,
    SiEpicgames,
    SiGogdotcom,
    SiGodotengine,
    SiSourceengine,
    SiUbisoft,
    SiUnrealengine,
} from "react-icons/si";
import { TbBrandElectronicArts } from "react-icons/tb";

export const iconMap: Record<string, IconType> = {
    apple: FaApple,
    mac: FaApple,
    linux: FaLinux,
    windows: FaWindows,
    "pc (microsoft windows)": FaWindows,
    win: FaWindows,
    xbox: FaXbox,
    xboxone: FaXbox,
    xbox360: FaXbox,
    "series-x-s": FaXbox,
    playstation: FaPlaystation,
    ps3: FaPlaystation,
    "ps4--1": FaPlaystation,
    ps5: FaPlaystation,
    steam: FaSteam,
    github: FaGithub,
    epic: SiEpicgames,
    battlenet: FaBattleNet,
    "battle-net": FaBattleNet,
    ea: TbBrandElectronicArts,
    gog: SiGogdotcom,
    itch: FaItchIo,
    itchio: FaItchIo,
    ubisoft: SiUbisoft,
    snes: FaGamepad,
    wii: FaGamepad,
    wiiu: FaGamepad,
    "new-3ds": FaGamepad,
    sfam: FaGamepad,
    arcade: FaGamepad,
    switch: BsNintendoSwitch,
    "switch-2": BsNintendoSwitch,
    cryengine: SiCryengine,
    godot: SiGodotengine,
    source: SiSourceengine,
    unity: FaUnity,
    unreal: SiUnrealengine,
    cart: FaShoppingCart,
    globe: FaGlobe,
    youtube: FaYoutube,
    twitch: FaTwitch,
    wikipedia: FaWikipediaW,
    discord: FaDiscord,
    android: FaAndroid,
    ios: FaAppStoreIos,
    twitter: FaTwitter,
};
