// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PlayAPISDK.Catalog.Games.Browse;
using PlayAPISDK.Catalog.Games.Item;
using PlayAPISDK.Catalog.Games.ReleaseDateRange;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PlayAPISDK.Catalog.Games
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\games
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GamesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The browse property</summary>
        public global::PlayAPISDK.Catalog.Games.Browse.BrowseRequestBuilder Browse
        {
            get => new global::PlayAPISDK.Catalog.Games.Browse.BrowseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The releaseDateRange property</summary>
        public global::PlayAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder ReleaseDateRange
        {
            get => new global::PlayAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the PlayAPISDK.catalog.games.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::PlayAPISDK.Catalog.Games.Item.WithGameItemRequestBuilder"/></returns>
        public global::PlayAPISDK.Catalog.Games.Item.WithGameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("gameId", position);
                return new global::PlayAPISDK.Catalog.Games.Item.WithGameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Games.GamesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/games", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Games.GamesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/games", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
