// <auto-generated/>
#pragma warning disable CS0618
using Ludus.Client.Api.User.Game.Status;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ludus.Client.Api.User.Game
{
    /// <summary>
    /// Builds and executes requests for operations under \api\user\game
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GameRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The status property</summary>
        public global::Ludus.Client.Api.User.Game.Status.StatusRequestBuilder Status
        {
            get => new global::Ludus.Client.Api.User.Game.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ludus.Client.Api.User.Game.GameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GameRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user/game", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ludus.Client.Api.User.Game.GameRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GameRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/user/game", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
