// <auto-generated/>
#pragma warning disable CS0618
using CatalogAPISDK.Catalog.Calendar;
using CatalogAPISDK.Catalog.Companies;
using CatalogAPISDK.Catalog.Events;
using CatalogAPISDK.Catalog.Games;
using CatalogAPISDK.Catalog.Igdb;
using CatalogAPISDK.Catalog.Steam;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CatalogAPISDK.Catalog
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CatalogRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The calendar property</summary>
        public global::CatalogAPISDK.Catalog.Calendar.CalendarRequestBuilder Calendar
        {
            get => new global::CatalogAPISDK.Catalog.Calendar.CalendarRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The companies property</summary>
        public global::CatalogAPISDK.Catalog.Companies.CompaniesRequestBuilder Companies
        {
            get => new global::CatalogAPISDK.Catalog.Companies.CompaniesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::CatalogAPISDK.Catalog.Events.EventsRequestBuilder Events
        {
            get => new global::CatalogAPISDK.Catalog.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The games property</summary>
        public global::CatalogAPISDK.Catalog.Games.GamesRequestBuilder Games
        {
            get => new global::CatalogAPISDK.Catalog.Games.GamesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The igdb property</summary>
        public global::CatalogAPISDK.Catalog.Igdb.IgdbRequestBuilder Igdb
        {
            get => new global::CatalogAPISDK.Catalog.Igdb.IgdbRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The steam property</summary>
        public global::CatalogAPISDK.Catalog.Steam.SteamRequestBuilder Steam
        {
            get => new global::CatalogAPISDK.Catalog.Steam.SteamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Catalog.CatalogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CatalogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Catalog.CatalogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CatalogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
