// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using PlayAPISDK.Catalog.Games.Item.Details;
using PlayAPISDK.Catalog.Games.Item.Hero;
using PlayAPISDK.Catalog.Games.Item.Links;
using PlayAPISDK.Catalog.Games.Item.Media;
using PlayAPISDK.Catalog.Games.Item.PageReleaseData;
using PlayAPISDK.Catalog.Games.Item.SimilarGames;
using PlayAPISDK.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace PlayAPISDK.Catalog.Games.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\games\{gameId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithGameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The details property</summary>
        public global::PlayAPISDK.Catalog.Games.Item.Details.DetailsRequestBuilder Details
        {
            get => new global::PlayAPISDK.Catalog.Games.Item.Details.DetailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hero property</summary>
        public global::PlayAPISDK.Catalog.Games.Item.Hero.HeroRequestBuilder Hero
        {
            get => new global::PlayAPISDK.Catalog.Games.Item.Hero.HeroRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The links property</summary>
        public global::PlayAPISDK.Catalog.Games.Item.Links.LinksRequestBuilder Links
        {
            get => new global::PlayAPISDK.Catalog.Games.Item.Links.LinksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The media property</summary>
        public global::PlayAPISDK.Catalog.Games.Item.Media.MediaRequestBuilder Media
        {
            get => new global::PlayAPISDK.Catalog.Games.Item.Media.MediaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pageReleaseData property</summary>
        public global::PlayAPISDK.Catalog.Games.Item.PageReleaseData.PageReleaseDataRequestBuilder PageReleaseData
        {
            get => new global::PlayAPISDK.Catalog.Games.Item.PageReleaseData.PageReleaseDataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The similarGames property</summary>
        public global::PlayAPISDK.Catalog.Games.Item.SimilarGames.SimilarGamesRequestBuilder SimilarGames
        {
            get => new global::PlayAPISDK.Catalog.Games.Item.SimilarGames.SimilarGamesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Games.Item.WithGameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/games/{gameId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Games.Item.WithGameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/games/{gameId}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::PlayAPISDK.Models.GetGameOverviewResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::PlayAPISDK.Models.GetGameOverviewResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::PlayAPISDK.Models.GetGameOverviewResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::PlayAPISDK.Models.GetGameOverviewResponse>(requestInfo, global::PlayAPISDK.Models.GetGameOverviewResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Catalog.Games.Item.WithGameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::PlayAPISDK.Catalog.Games.Item.WithGameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::PlayAPISDK.Catalog.Games.Item.WithGameItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithGameItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
