/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GamesGameRouteImport } from './routes/games/$game'

const GamesGameRoute = GamesGameRouteImport.update({
  id: '/games/$game',
  path: '/games/$game',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/games/$game': typeof GamesGameRoute
}
export interface FileRoutesByTo {
  '/games/$game': typeof GamesGameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/games/$game': typeof GamesGameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/games/$game'
  fileRoutesByTo: FileRoutesByTo
  to: '/games/$game'
  id: '__root__' | '/games/$game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GamesGameRoute: typeof GamesGameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/games/$game': {
      id: '/games/$game'
      path: '/games/$game'
      fullPath: '/games/$game'
      preLoaderRoute: typeof GamesGameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  GamesGameRoute: GamesGameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
