CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pg_search;

CREATE TABLE companies (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    start_date timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    metadata jsonb NOT NULL,
    parent_id bigint,
    changed_company_id bigint,
    CONSTRAINT pk_companies PRIMARY KEY (id),
    CONSTRAINT fk_companies_companies_changed_company_id FOREIGN KEY (changed_company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_companies_companies_parent_id FOREIGN KEY (parent_id) REFERENCES companies (id) ON DELETE RESTRICT
);

CREATE TABLE franchises (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    metadata jsonb NOT NULL,
    CONSTRAINT pk_franchises PRIMARY KEY (id)
);

CREATE TABLE game_engines (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    metadata jsonb NOT NULL,
    logo jsonb,
    CONSTRAINT pk_game_engines PRIMARY KEY (id)
);

CREATE TABLE game_modes (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_game_modes PRIMARY KEY (id)
);

CREATE TABLE games (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    game_type bigint NOT NULL,
    rating double precision,
    rating_count bigint,
    total_rating double precision,
    total_rating_count bigint,
    url text NOT NULL,
    first_release_date timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    metadata jsonb NOT NULL,
    game_entity_id bigint,
    CONSTRAINT pk_games PRIMARY KEY (id),
    CONSTRAINT fk_games_games_game_entity_id FOREIGN KEY (game_entity_id) REFERENCES games (id)
);

CREATE TABLE genres (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE platforms (
    id bigint NOT NULL,
    name text NOT NULL,
    abbreviation text,
    generation bigint,
    slug text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    logo jsonb,
    CONSTRAINT pk_platforms PRIMARY KEY (id)
);

CREATE TABLE player_perspectives (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_player_perspectives PRIMARY KEY (id)
);

CREATE TABLE themes (
    id bigint NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_themes PRIMARY KEY (id)
);

CREATE TABLE developer_game (
    company_id bigint NOT NULL,
    game_id bigint NOT NULL,
    CONSTRAINT pk_developer_game PRIMARY KEY (company_id, game_id),
    CONSTRAINT fk_developer_game_companies_company_id FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    CONSTRAINT fk_developer_game_games_game_id FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE
);

CREATE TABLE franchise_entity_game_entity (
    franchises_id bigint NOT NULL,
    games_id bigint NOT NULL,
    CONSTRAINT pk_franchise_entity_game_entity PRIMARY KEY (franchises_id, games_id),
    CONSTRAINT fk_franchise_entity_game_entity_franchises_franchises_id FOREIGN KEY (franchises_id) REFERENCES franchises (id) ON DELETE CASCADE,
    CONSTRAINT fk_franchise_entity_game_entity_games_games_id FOREIGN KEY (games_id) REFERENCES games (id) ON DELETE CASCADE
);

CREATE TABLE game_engine_entity_game_entity (
    game_engines_id bigint NOT NULL,
    games_id bigint NOT NULL,
    CONSTRAINT pk_game_engine_entity_game_entity PRIMARY KEY (game_engines_id, games_id),
    CONSTRAINT fk_game_engine_entity_game_entity_game_engines_game_engines_id FOREIGN KEY (game_engines_id) REFERENCES game_engines (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_engine_entity_game_entity_games_games_id FOREIGN KEY (games_id) REFERENCES games (id) ON DELETE CASCADE
);

CREATE TABLE game_entity_game_mode_entity (
    game_modes_id bigint NOT NULL,
    games_id bigint NOT NULL,
    CONSTRAINT pk_game_entity_game_mode_entity PRIMARY KEY (game_modes_id, games_id),
    CONSTRAINT fk_game_entity_game_mode_entity_game_modes_game_modes_id FOREIGN KEY (game_modes_id) REFERENCES game_modes (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_entity_game_mode_entity_games_games_id FOREIGN KEY (games_id) REFERENCES games (id) ON DELETE CASCADE
);

CREATE TABLE publisher_game (
    company_id bigint NOT NULL,
    game_id bigint NOT NULL,
    CONSTRAINT pk_publisher_game PRIMARY KEY (company_id, game_id),
    CONSTRAINT fk_publisher_game_companies_company_id FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    CONSTRAINT fk_publisher_game_games_game_id FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE
);

CREATE TABLE game_entity_genre_entity (
    games_id bigint NOT NULL,
    genres_id bigint NOT NULL,
    CONSTRAINT pk_game_entity_genre_entity PRIMARY KEY (games_id, genres_id),
    CONSTRAINT fk_game_entity_genre_entity_games_games_id FOREIGN KEY (games_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_entity_genre_entity_genres_genres_id FOREIGN KEY (genres_id) REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE game_entity_platform_entity (
    games_id bigint NOT NULL,
    platforms_id bigint NOT NULL,
    CONSTRAINT pk_game_entity_platform_entity PRIMARY KEY (games_id, platforms_id),
    CONSTRAINT fk_game_entity_platform_entity_games_games_id FOREIGN KEY (games_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_entity_platform_entity_platforms_platforms_id FOREIGN KEY (platforms_id) REFERENCES platforms (id) ON DELETE CASCADE
);

CREATE TABLE game_entity_player_perspective_entity (
    games_id bigint NOT NULL,
    player_perspectives_id bigint NOT NULL,
    CONSTRAINT pk_game_entity_player_perspective_entity PRIMARY KEY (games_id, player_perspectives_id),
    CONSTRAINT fk_game_entity_player_perspective_entity_games_games_id FOREIGN KEY (games_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_entity_player_perspective_entity_player_perspectives_p FOREIGN KEY (player_perspectives_id) REFERENCES player_perspectives (id) ON DELETE CASCADE
);

CREATE TABLE game_entity_theme_entity (
    games_id bigint NOT NULL,
    themes_id bigint NOT NULL,
    CONSTRAINT pk_game_entity_theme_entity PRIMARY KEY (games_id, themes_id),
    CONSTRAINT fk_game_entity_theme_entity_games_games_id FOREIGN KEY (games_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_entity_theme_entity_themes_themes_id FOREIGN KEY (themes_id) REFERENCES themes (id) ON DELETE CASCADE
);

CREATE INDEX ix_companies_changed_company_id ON companies (changed_company_id);

CREATE INDEX ix_companies_parent_id ON companies (parent_id);

CREATE INDEX ix_developer_game_game_id ON developer_game (game_id);

CREATE INDEX ix_franchise_entity_game_entity_games_id ON franchise_entity_game_entity (games_id);

CREATE INDEX ix_game_engine_entity_game_entity_games_id ON game_engine_entity_game_entity (games_id);

CREATE INDEX ix_game_entity_game_mode_entity_games_id ON game_entity_game_mode_entity (games_id);

CREATE INDEX ix_game_entity_genre_entity_genres_id ON game_entity_genre_entity (genres_id);

CREATE INDEX ix_game_entity_platform_entity_platforms_id ON game_entity_platform_entity (platforms_id);

CREATE INDEX ix_game_entity_player_perspective_entity_player_perspectives_id ON game_entity_player_perspective_entity (player_perspectives_id);

CREATE INDEX ix_game_entity_theme_entity_themes_id ON game_entity_theme_entity (themes_id);

CREATE INDEX ix_games_game_entity_id ON games (game_entity_id);

CREATE INDEX ix_publisher_game_game_id ON publisher_game (game_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20251116222936_Initial', '10.0.0-rc.2.25502.107');

COMMIT;

