CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pg_search;

CREATE TABLE "Companies" (
    "Id" bigint NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Added" timestamp with time zone NOT NULL,
    "Metadata" jsonb NOT NULL,
    "ParentId" bigint,
    "ChangedCompanyId" bigint,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Companies_Companies_ChangedCompanyId" FOREIGN KEY ("ChangedCompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Companies_Companies_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Franchises" (
    "Id" bigint NOT NULL,
    "Metadata" jsonb NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Added" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Franchises" PRIMARY KEY ("Id")
);

CREATE TABLE "GameEngines" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "Url" text NOT NULL,
    "Metadata" jsonb NOT NULL,
    "Logo" jsonb,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GameEngines" PRIMARY KEY ("Id")
);

CREATE TABLE "GameModes" (
    "Id" bigint NOT NULL,
    "CreatedAt" bigint NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Url" text NOT NULL,
    CONSTRAINT "PK_GameModes" PRIMARY KEY ("Id")
);

CREATE TABLE "Genres" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "Url" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
);

CREATE TABLE "Platforms" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Abbreviation" text,
    "Generation" bigint,
    "Logo" jsonb,
    "Slug" text,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Platforms" PRIMARY KEY ("Id")
);

CREATE TABLE "PlayerPerspectiveEntity" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Url" text NOT NULL,
    CONSTRAINT "PK_PlayerPerspectiveEntity" PRIMARY KEY ("Id")
);

CREATE TABLE "Themes" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "Url" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Themes" PRIMARY KEY ("Id")
);

CREATE TABLE "Games" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "GameType" bigint NOT NULL,
    "Rating" double precision,
    "RatingCount" bigint,
    "TotalRating" double precision,
    "TotalRatingCount" bigint,
    "FirstReleaseDate" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Metadata" jsonb NOT NULL,
    "FranchiseEntityId" bigint,
    "GameEntityId" bigint,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Games_Franchises_FranchiseEntityId" FOREIGN KEY ("FranchiseEntityId") REFERENCES "Franchises" ("Id"),
    CONSTRAINT "FK_Games_Games_GameEntityId" FOREIGN KEY ("GameEntityId") REFERENCES "Games" ("Id")
);

CREATE TABLE "DeveloperGame" (
    "DevelopedId" bigint NOT NULL,
    "DevelopersId" bigint NOT NULL,
    CONSTRAINT "PK_DeveloperGame" PRIMARY KEY ("DevelopedId", "DevelopersId"),
    CONSTRAINT "FK_DeveloperGame_Companies_DevelopersId" FOREIGN KEY ("DevelopersId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DeveloperGame_Games_DevelopedId" FOREIGN KEY ("DevelopedId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GameEngineEntityGameEntity" (
    "GameEnginesId" bigint NOT NULL,
    "GamesId" bigint NOT NULL,
    CONSTRAINT "PK_GameEngineEntityGameEntity" PRIMARY KEY ("GameEnginesId", "GamesId"),
    CONSTRAINT "FK_GameEngineEntityGameEntity_GameEngines_GameEnginesId" FOREIGN KEY ("GameEnginesId") REFERENCES "GameEngines" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GameEngineEntityGameEntity_Games_GamesId" FOREIGN KEY ("GamesId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GameEntityGameModeEntity" (
    "GameModesId" bigint NOT NULL,
    "GamesId" bigint NOT NULL,
    CONSTRAINT "PK_GameEntityGameModeEntity" PRIMARY KEY ("GameModesId", "GamesId"),
    CONSTRAINT "FK_GameEntityGameModeEntity_GameModes_GameModesId" FOREIGN KEY ("GameModesId") REFERENCES "GameModes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GameEntityGameModeEntity_Games_GamesId" FOREIGN KEY ("GamesId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GameEntityGenreEntity" (
    "GenresId" bigint NOT NULL,
    "GenresId1" bigint NOT NULL,
    CONSTRAINT "PK_GameEntityGenreEntity" PRIMARY KEY ("GenresId", "GenresId1"),
    CONSTRAINT "FK_GameEntityGenreEntity_Games_GenresId" FOREIGN KEY ("GenresId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GameEntityGenreEntity_Genres_GenresId1" FOREIGN KEY ("GenresId1") REFERENCES "Genres" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GameEntityPlatformEntity" (
    "GamesId" bigint NOT NULL,
    "PlatformsId" bigint NOT NULL,
    CONSTRAINT "PK_GameEntityPlatformEntity" PRIMARY KEY ("GamesId", "PlatformsId"),
    CONSTRAINT "FK_GameEntityPlatformEntity_Games_GamesId" FOREIGN KEY ("GamesId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GameEntityPlatformEntity_Platforms_PlatformsId" FOREIGN KEY ("PlatformsId") REFERENCES "Platforms" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GameEntityPlayerPerspectiveEntity" (
    "GamesId" bigint NOT NULL,
    "PlayerPerspectivesId" bigint NOT NULL,
    CONSTRAINT "PK_GameEntityPlayerPerspectiveEntity" PRIMARY KEY ("GamesId", "PlayerPerspectivesId"),
    CONSTRAINT "FK_GameEntityPlayerPerspectiveEntity_Games_GamesId" FOREIGN KEY ("GamesId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GameEntityPlayerPerspectiveEntity_PlayerPerspectiveEntity_P~" FOREIGN KEY ("PlayerPerspectivesId") REFERENCES "PlayerPerspectiveEntity" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GameEntityThemeEntity" (
    "GamesId" bigint NOT NULL,
    "ThemesId" bigint NOT NULL,
    CONSTRAINT "PK_GameEntityThemeEntity" PRIMARY KEY ("GamesId", "ThemesId"),
    CONSTRAINT "FK_GameEntityThemeEntity_Games_GamesId" FOREIGN KEY ("GamesId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GameEntityThemeEntity_Themes_ThemesId" FOREIGN KEY ("ThemesId") REFERENCES "Themes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PublisherGame" (
    "PublishedId" bigint NOT NULL,
    "PublishersId" bigint NOT NULL,
    CONSTRAINT "PK_PublisherGame" PRIMARY KEY ("PublishedId", "PublishersId"),
    CONSTRAINT "FK_PublisherGame_Companies_PublishersId" FOREIGN KEY ("PublishersId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PublisherGame_Games_PublishedId" FOREIGN KEY ("PublishedId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Companies_ChangedCompanyId" ON "Companies" ("ChangedCompanyId");

CREATE INDEX "IX_Companies_ParentId" ON "Companies" ("ParentId");

CREATE INDEX "IX_DeveloperGame_DevelopersId" ON "DeveloperGame" ("DevelopersId");

CREATE INDEX "IX_GameEngineEntityGameEntity_GamesId" ON "GameEngineEntityGameEntity" ("GamesId");

CREATE INDEX "IX_GameEntityGameModeEntity_GamesId" ON "GameEntityGameModeEntity" ("GamesId");

CREATE INDEX "IX_GameEntityGenreEntity_GenresId1" ON "GameEntityGenreEntity" ("GenresId1");

CREATE INDEX "IX_GameEntityPlatformEntity_PlatformsId" ON "GameEntityPlatformEntity" ("PlatformsId");

CREATE INDEX "IX_GameEntityPlayerPerspectiveEntity_PlayerPerspectivesId" ON "GameEntityPlayerPerspectiveEntity" ("PlayerPerspectivesId");

CREATE INDEX "IX_GameEntityThemeEntity_ThemesId" ON "GameEntityThemeEntity" ("ThemesId");

CREATE INDEX "IX_Games_FranchiseEntityId" ON "Games" ("FranchiseEntityId");

CREATE INDEX "IX_Games_GameEntityId" ON "Games" ("GameEntityId");

CREATE INDEX "IX_PublisherGame_PublishersId" ON "PublisherGame" ("PublishersId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251023211228_Initial', '10.0.0-rc.1.25451.107');

COMMIT;

