/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationQueryKey, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, InfiniteQueryPageParamsOptions, InvalidateOptions, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, Updater } from "@tanstack/query-core";
import type { DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, UseInfiniteQueryResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface AuthService {
    getSteamresponse: {
        /**/
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError> | QueryFiltersByQueryKey<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>, options?: CancelOptions): Promise<void>;
        /**/
        getQueryKey(parameters: DeepReadonly<GetSteamresponseParameters> | void): ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.authService.getSteamresponse.useQuery()
         * ```
         */
        useQuery<TData = GetSteamresponseData>(parameters: ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void), options?: Omit<UndefinedInitialDataOptions<GetSteamresponseData, GetSteamresponseError, TData, ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>>, "queryKey">): UseQueryResult<TData, GetSteamresponseError | Error>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.authService.getSteamresponse.useQuery()
         * ```
         */
        useQuery<TData = GetSteamresponseData>(parameters: ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void), options: Omit<DefinedInitialDataOptions<GetSteamresponseData, GetSteamresponseError, TData, ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>>, "queryKey">): DefinedUseQueryResult<TData, GetSteamresponseError | Error>;
        /**/
        fetchInfiniteQuery<TPageParam extends GetSteamresponseParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetSteamresponseSchema, GetSteamresponseData, GetSteamresponseParameters, DeepReadonly<TPageParam>, GetSteamresponseError> | void): Promise<OperationInfiniteData<GetSteamresponseData, GetSteamresponseParameters>>;
        /**/
        prefetchInfiniteQuery<TPageParam extends GetSteamresponseParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetSteamresponseSchema, GetSteamresponseData, GetSteamresponseParameters, DeepReadonly<TPageParam>, GetSteamresponseError> | void): Promise<void>;
        /**/
        ensureInfiniteQueryData<TPageParam extends GetSteamresponseParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<GetSteamresponseSchema, GetSteamresponseData, GetSteamresponseParameters, DeepReadonly<TPageParam>, GetSteamresponseError> | void): Promise<OperationInfiniteData<GetSteamresponseData, GetSteamresponseParameters>>;
        /**/
        fetchQuery(options: ServiceOperationFetchQueryOptions<GetSteamresponseSchema, GetSteamresponseData, GetSteamresponseParameters, GetSteamresponseError> | void): Promise<GetSteamresponseData>;
        /**/
        prefetchQuery(options: ServiceOperationFetchQueryOptions<GetSteamresponseSchema, GetSteamresponseData, GetSteamresponseParameters, GetSteamresponseError> | void): Promise<void>;
        /**/
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<GetSteamresponseSchema, GetSteamresponseData, GetSteamresponseParameters, GetSteamresponseError> | void): Promise<GetSteamresponseData>;
        /**/
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void)): OperationInfiniteData<GetSteamresponseData, GetSteamresponseParameters> | undefined;
        /**/
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError> | QueryFiltersByQueryKey<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>,
            data: NoInfer<OperationInfiniteData<GetSteamresponseData, GetSteamresponseParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>,
            data: GetSteamresponseData | undefined
        ]>;
        /**/
        getQueryData(parameters: ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void)): GetSteamresponseData | undefined;
        /**/
        getQueryState(parameters: ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void)): QueryState<GetSteamresponseData, GetSteamresponseError> | undefined;
        /**/
        getInfiniteQueryState(parameters: DeepReadonly<GetSteamresponseParameters> | ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | void): QueryState<OperationInfiniteData<GetSteamresponseData, GetSteamresponseParameters>, GetSteamresponseError> | undefined;
        /**/
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>, options?: InvalidateOptions): Promise<void>;
        /**/
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError> | QueryFiltersByQueryKey<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>): number;
        /**/
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<GetSteamresponseSchema, GetSteamresponseParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<GetSteamresponseParameters, TMeta, TSignal> | void), client?: (schema: GetSteamresponseSchema, options: {
            parameters: GetSteamresponseParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<GetSteamresponseData, GetSteamresponseError>>): Promise<RequestFnResponse<GetSteamresponseData, GetSteamresponseError>>;
        /**/
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError> | QueryFiltersByQueryKey<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>, options?: RefetchOptions): Promise<void>;
        /**/
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError> | QueryFiltersByQueryKey<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>): void;
        /**/
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError> | QueryFiltersByQueryKey<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>, options?: ResetOptions): Promise<void>;
        /**/
        setInfiniteQueryData(parameters: (DeepReadonly<GetSteamresponseParameters> | undefined) | ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>, updater: Updater<NoInfer<OperationInfiniteData<GetSteamresponseData, GetSteamresponseParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<GetSteamresponseData, GetSteamresponseParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<GetSteamresponseData, GetSteamresponseParameters> | undefined;
        /**/
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError> | QueryFiltersByQueryKey<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>, updater: Updater<NoInfer<GetSteamresponseData> | undefined, NoInfer<GetSteamresponseData> | undefined>, options?: SetDataOptions): Array<GetSteamresponseData | undefined>;
        /**/
        setQueryData(parameters: (DeepReadonly<GetSteamresponseParameters> | undefined) | ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>, updater: Updater<NoInfer<GetSteamresponseData> | undefined, NoInfer<DeepReadonly<GetSteamresponseData>> | undefined>, options?: SetDataOptions): GetSteamresponseData | undefined;
        /**/
        getInfiniteQueryKey(parameters: DeepReadonly<GetSteamresponseParameters> | void): ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.authService.getSteamresponse.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetSteamresponseParameters, TQueryFnData = GetSteamresponseData, TData = OperationInfiniteData<TQueryFnData, GetSteamresponseParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, GetSteamresponseError, TData, ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, GetSteamresponseError | Error>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.authService.getSteamresponse.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetSteamresponseParameters, TQueryFnData = GetSteamresponseData, TData = OperationInfiniteData<TQueryFnData, GetSteamresponseParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, GetSteamresponseError, TData, ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetSteamresponseData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, GetSteamresponseError | Error>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const getSteamresponseTotal = qraft.authService.getSteamresponse.useIsFetching()
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError> | QueryFiltersByQueryKey<GetSteamresponseSchema, GetSteamresponseData, TInfinite, GetSteamresponseParameters, GetSteamresponseError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const getSteamresponseResults = qraft.authService.getSteamresponse.useQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * getSteamresponseResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const getSteamresponseCombinedResults = qraft.authService.getSteamresponse.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * getSteamresponseCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<GetSteamresponseSchema, GetSteamresponseParameters, GetSteamresponseData, GetSteamresponseError>>, TCombinedResult = Array<UseQueryResult<GetSteamresponseData, GetSteamresponseError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<GetSteamresponseData, GetSteamresponseError>>) => TCombinedResult;
        }): TCombinedResult;
        /**/
        getQueryKey(parameters: DeepReadonly<GetSteamresponseParameters> | void): ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.authService.getSteamresponse.useQuery()
         * ```
         */
        useQuery<TData = GetSteamresponseData>(parameters: ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void), options?: Omit<UndefinedInitialDataOptions<GetSteamresponseData, GetSteamresponseError, TData, ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>>, "queryKey">): UseQueryResult<TData, GetSteamresponseError | Error>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.authService.getSteamresponse.useQuery()
         * ```
         */
        useQuery<TData = GetSteamresponseData>(parameters: ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void), options: Omit<DefinedInitialDataOptions<GetSteamresponseData, GetSteamresponseError, TData, ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>>, "queryKey">): DefinedUseQueryResult<TData, GetSteamresponseError | Error>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.authService.getSteamresponse.useSuspenseInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends GetSteamresponseParameters, TData = GetSteamresponseData>(parameters: ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void), options: Omit<UseSuspenseInfiniteQueryOptions<GetSteamresponseData, GetSteamresponseError, OperationInfiniteData<TData, GetSteamresponseParameters>, GetSteamresponseData, ServiceOperationInfiniteQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetSteamresponseData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, GetSteamresponseParameters>, GetSteamresponseError | Error>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const getSteamresponseData = qraft.authService.getSteamresponse.useSuspenseQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * getSteamresponseResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const getSteamresponseCombinedData = qraft.authService.getSteamresponse.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * getSteamresponseCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<GetSteamresponseSchema, GetSteamresponseParameters, GetSteamresponseData, GetSteamresponseError>>, TCombinedResult = Array<UseSuspenseQueryResult<GetSteamresponseData, GetSteamresponseError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<GetSteamresponseData, GetSteamresponseError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query without parameters
         * ```ts
         * const data = qraft.authService.getSteamresponse.useSuspenseQuery()
         * ```
         */
        useSuspenseQuery<TData = GetSteamresponseData>(parameters: ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters> | (DeepReadonly<GetSteamresponseParameters> | void), options?: Omit<UseSuspenseQueryOptions<GetSteamresponseData, GetSteamresponseError, TData, ServiceOperationQueryKey<GetSteamresponseSchema, GetSteamresponseParameters>>, "queryKey">): UseSuspenseQueryResult<TData, GetSteamresponseError | Error>;
        schema: GetSteamresponseSchema;
        types: {
            parameters: GetSteamresponseParameters;
            data: GetSteamresponseData;
            error: GetSteamresponseError;
        };
    };
}
export const getSteamresponse = {
    schema: {
        method: "get",
        url: "/Auth/steamresponse"
    }
} as {
    schema: GetSteamresponseSchema;
    [QraftServiceOperationsToken]: AuthService["getSteamresponse"];
};
export const authService = {
    getSteamresponse
} as const;
type GetSteamresponseSchema = {
    method: "get";
    url: "/Auth/steamresponse";
};
type GetSteamresponseParameters = undefined;
type GetSteamresponseData = null;
type GetSteamresponseError = unknown;
