[runtime]
log_level="WARNING"  # the system log level of dlt
dlthub_telemetry = false

[normalize.data_writer]
disable_compression=true

[destination.filesystem]
kwargs = '{"auto_mkdir": true}'
layout="{table_name}/{load_id}.{file_id}.{ext}"
bucket_url = '\\localhost\d$\Projects\ProjectLudus\filesys'

[sources.filesystem]
local_dir = '\\localhost\d$\Projects\ProjectLudus\filesys' # fill this in!
bucket_url = '\\localhost\d$\Projects\ProjectLudus\filesys'

[destination.duckdb]
extensions=["spatial"]
pragmas=["enable_progress_bar", "enable_logging"]