// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PlayAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CompanyOverviewDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The country property</summary>
        public long? Country { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The logoId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogoId { get; set; }
#nullable restore
#else
        public string LogoId { get; set; }
#endif
        /// <summary>The logoImageId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogoImageId { get; set; }
#nullable restore
#else
        public string LogoImageId { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parentCompany property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PlayAPISDK.Models.CompanyOverviewDto.CompanyOverviewDto_parentCompany? ParentCompany { get; set; }
#nullable restore
#else
        public global::PlayAPISDK.Models.CompanyOverviewDto.CompanyOverviewDto_parentCompany ParentCompany { get; set; }
#endif
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The startDate property</summary>
        public long? StartDate { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Models.CompanyOverviewDto"/> and sets the default values.
        /// </summary>
        public CompanyOverviewDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Models.CompanyOverviewDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PlayAPISDK.Models.CompanyOverviewDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PlayAPISDK.Models.CompanyOverviewDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "country", n => { Country = n.GetLongValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "logoId", n => { LogoId = n.GetStringValue(); } },
                { "logoImageId", n => { LogoImageId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parentCompany", n => { ParentCompany = n.GetObjectValue<global::PlayAPISDK.Models.CompanyOverviewDto.CompanyOverviewDto_parentCompany>(global::PlayAPISDK.Models.CompanyOverviewDto.CompanyOverviewDto_parentCompany.CreateFromDiscriminatorValue); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "startDate", n => { StartDate = n.GetLongValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("country", Country);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("logoId", LogoId);
            writer.WriteStringValue("logoImageId", LogoImageId);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::PlayAPISDK.Models.CompanyOverviewDto.CompanyOverviewDto_parentCompany>("parentCompany", ParentCompany);
            writer.WriteStringValue("slug", Slug);
            writer.WriteLongValue("startDate", StartDate);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::PlayAPISDK.Models.CompanyOverviewDto_parentCompanyMember1"/>, <see cref="global::PlayAPISDK.Models.ParentCompanyDto"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompanyOverviewDto_parentCompany : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::PlayAPISDK.Models.CompanyOverviewDto_parentCompanyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PlayAPISDK.Models.CompanyOverviewDto_parentCompanyMember1? CompanyOverviewDtoParentCompanyMember1 { get; set; }
#nullable restore
#else
            public global::PlayAPISDK.Models.CompanyOverviewDto_parentCompanyMember1 CompanyOverviewDtoParentCompanyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PlayAPISDK.Models.ParentCompanyDto"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PlayAPISDK.Models.ParentCompanyDto? ParentCompanyDto { get; set; }
#nullable restore
#else
            public global::PlayAPISDK.Models.ParentCompanyDto ParentCompanyDto { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::PlayAPISDK.Models.CompanyOverviewDto.CompanyOverviewDto_parentCompany"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::PlayAPISDK.Models.CompanyOverviewDto.CompanyOverviewDto_parentCompany CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::PlayAPISDK.Models.CompanyOverviewDto.CompanyOverviewDto_parentCompany();
                if("ParentCompanyDto".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParentCompanyDto = new global::PlayAPISDK.Models.ParentCompanyDto();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CompanyOverviewDtoParentCompanyMember1 != null)
                {
                    return CompanyOverviewDtoParentCompanyMember1.GetFieldDeserializers();
                }
                else if(ParentCompanyDto != null)
                {
                    return ParentCompanyDto.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CompanyOverviewDtoParentCompanyMember1 != null)
                {
                    writer.WriteObjectValue<global::PlayAPISDK.Models.CompanyOverviewDto_parentCompanyMember1>(null, CompanyOverviewDtoParentCompanyMember1);
                }
                else if(ParentCompanyDto != null)
                {
                    writer.WriteObjectValue<global::PlayAPISDK.Models.ParentCompanyDto>(null, ParentCompanyDto);
                }
            }
        }
    }
}
#pragma warning restore CS0618
