// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PlayAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GameMediaDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The screenshots property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Screenshots { get; set; }
#nullable restore
#else
        public List<string> Screenshots { get; set; }
#endif
        /// <summary>The videos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PlayAPISDK.Models.GameMediaVideoDto>? Videos { get; set; }
#nullable restore
#else
        public List<global::PlayAPISDK.Models.GameMediaVideoDto> Videos { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Models.GameMediaDto"/> and sets the default values.
        /// </summary>
        public GameMediaDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Models.GameMediaDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PlayAPISDK.Models.GameMediaDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PlayAPISDK.Models.GameMediaDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "screenshots", n => { Screenshots = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "videos", n => { Videos = n.GetCollectionOfObjectValues<global::PlayAPISDK.Models.GameMediaVideoDto>(global::PlayAPISDK.Models.GameMediaVideoDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("screenshots", Screenshots);
            writer.WriteCollectionOfObjectValues<global::PlayAPISDK.Models.GameMediaVideoDto>("videos", Videos);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
