// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PlayAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListHistoryEntry : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action property</summary>
        public global::PlayAPISDK.Models.ListAction? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The gameId property</summary>
        public long? GameId { get; set; }
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The list property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PlayAPISDK.Models.UserList? List { get; set; }
#nullable restore
#else
        public global::PlayAPISDK.Models.UserList List { get; set; }
#endif
        /// <summary>The listId property</summary>
        public Guid? ListId { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PlayAPISDK.Models.User? User { get; set; }
#nullable restore
#else
        public global::PlayAPISDK.Models.User User { get; set; }
#endif
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Models.ListHistoryEntry"/> and sets the default values.
        /// </summary>
        public ListHistoryEntry()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Models.ListHistoryEntry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PlayAPISDK.Models.ListHistoryEntry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::PlayAPISDK.Models.ListHistoryEntry();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::PlayAPISDK.Models.ListAction>(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "gameId", n => { GameId = n.GetLongValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "list", n => { List = n.GetObjectValue<global::PlayAPISDK.Models.UserList>(global::PlayAPISDK.Models.UserList.CreateFromDiscriminatorValue); } },
                { "listId", n => { ListId = n.GetGuidValue(); } },
                { "user", n => { User = n.GetObjectValue<global::PlayAPISDK.Models.User>(global::PlayAPISDK.Models.User.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::PlayAPISDK.Models.ListAction>("action", Action);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteLongValue("gameId", GameId);
            writer.WriteLongValue("id", Id);
            writer.WriteObjectValue<global::PlayAPISDK.Models.UserList>("list", List);
            writer.WriteGuidValue("listId", ListId);
            writer.WriteObjectValue<global::PlayAPISDK.Models.User>("user", User);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
