// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PlayAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SteamData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The capsuleUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CapsuleUrl { get; set; }
#nullable restore
#else
        public string CapsuleUrl { get; set; }
#endif
        /// <summary>The currentPlayers property</summary>
        public long? CurrentPlayers { get; set; }
        /// <summary>The headerUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderUrl { get; set; }
#nullable restore
#else
        public string HeaderUrl { get; set; }
#endif
        /// <summary>The peak24h property</summary>
        public long? Peak24h { get; set; }
        /// <summary>The steamAppId property</summary>
        public long? SteamAppId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Models.SteamData"/> and sets the default values.
        /// </summary>
        public SteamData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Models.SteamData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PlayAPISDK.Models.SteamData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::PlayAPISDK.Models.SteamData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "capsuleUrl", n => { CapsuleUrl = n.GetStringValue(); } },
                { "currentPlayers", n => { CurrentPlayers = n.GetLongValue(); } },
                { "headerUrl", n => { HeaderUrl = n.GetStringValue(); } },
                { "peak24h", n => { Peak24h = n.GetLongValue(); } },
                { "steamAppId", n => { SteamAppId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("capsuleUrl", CapsuleUrl);
            writer.WriteLongValue("currentPlayers", CurrentPlayers);
            writer.WriteStringValue("headerUrl", HeaderUrl);
            writer.WriteLongValue("peak24h", Peak24h);
            writer.WriteLongValue("steamAppId", SteamAppId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
