// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PlayAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SteamPricingData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The discountPercent property</summary>
        public int? DiscountPercent { get; set; }
        /// <summary>The finalCents property</summary>
        public int? FinalCents { get; set; }
        /// <summary>The finalFormatted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinalFormatted { get; set; }
#nullable restore
#else
        public string FinalFormatted { get; set; }
#endif
        /// <summary>The high30d property</summary>
        public int? High30d { get; set; }
        /// <summary>The initialCents property</summary>
        public int? InitialCents { get; set; }
        /// <summary>The initialFormatted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InitialFormatted { get; set; }
#nullable restore
#else
        public string InitialFormatted { get; set; }
#endif
        /// <summary>The low30d property</summary>
        public int? Low30d { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Models.SteamPricingData"/> and sets the default values.
        /// </summary>
        public SteamPricingData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Models.SteamPricingData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PlayAPISDK.Models.SteamPricingData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PlayAPISDK.Models.SteamPricingData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "discountPercent", n => { DiscountPercent = n.GetIntValue(); } },
                { "finalCents", n => { FinalCents = n.GetIntValue(); } },
                { "finalFormatted", n => { FinalFormatted = n.GetStringValue(); } },
                { "high30d", n => { High30d = n.GetIntValue(); } },
                { "initialCents", n => { InitialCents = n.GetIntValue(); } },
                { "initialFormatted", n => { InitialFormatted = n.GetStringValue(); } },
                { "low30d", n => { Low30d = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currency", Currency);
            writer.WriteIntValue("discountPercent", DiscountPercent);
            writer.WriteIntValue("finalCents", FinalCents);
            writer.WriteStringValue("finalFormatted", FinalFormatted);
            writer.WriteIntValue("high30d", High30d);
            writer.WriteIntValue("initialCents", InitialCents);
            writer.WriteStringValue("initialFormatted", InitialFormatted);
            writer.WriteIntValue("low30d", Low30d);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
