// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PlayAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserList : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The history property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PlayAPISDK.Models.ListHistoryEntry>? History { get; set; }
#nullable restore
#else
        public List<global::PlayAPISDK.Models.ListHistoryEntry> History { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isDefault property</summary>
        public bool? IsDefault { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PlayAPISDK.Models.ListItem>? Items { get; set; }
#nullable restore
#else
        public List<global::PlayAPISDK.Models.ListItem> Items { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PlayAPISDK.Models.User? User { get; set; }
#nullable restore
#else
        public global::PlayAPISDK.Models.User User { get; set; }
#endif
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>The visibility property</summary>
        public global::PlayAPISDK.Models.ListVisibility? Visibility { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Models.UserList"/> and sets the default values.
        /// </summary>
        public UserList()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Models.UserList"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PlayAPISDK.Models.UserList CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::PlayAPISDK.Models.UserList();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "history", n => { History = n.GetCollectionOfObjectValues<global::PlayAPISDK.Models.ListHistoryEntry>(global::PlayAPISDK.Models.ListHistoryEntry.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isDefault", n => { IsDefault = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::PlayAPISDK.Models.ListItem>(global::PlayAPISDK.Models.ListItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "user", n => { User = n.GetObjectValue<global::PlayAPISDK.Models.User>(global::PlayAPISDK.Models.User.CreateFromDiscriminatorValue); } },
                { "userId", n => { UserId = n.GetGuidValue(); } },
                { "visibility", n => { Visibility = n.GetEnumValue<global::PlayAPISDK.Models.ListVisibility>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::PlayAPISDK.Models.ListHistoryEntry>("history", History);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isDefault", IsDefault);
            writer.WriteCollectionOfObjectValues<global::PlayAPISDK.Models.ListItem>("items", Items);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteObjectValue<global::PlayAPISDK.Models.User>("user", User);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteEnumValue<global::PlayAPISDK.Models.ListVisibility>("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
