// <auto-generated/>
#pragma warning disable CS0618
using CatalogAPISDK.Api.Me.Games.Item.Lists;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CatalogAPISDK.Api.Me.Games.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\me\games\{gameId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithGameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lists property</summary>
        public global::CatalogAPISDK.Api.Me.Games.Item.Lists.ListsRequestBuilder Lists
        {
            get => new global::CatalogAPISDK.Api.Me.Games.Item.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Api.Me.Games.Item.WithGameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/me/games/{gameId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Api.Me.Games.Item.WithGameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/me/games/{gameId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
