/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { WeatherForecastGetQueryResponse } from '../../types/WeatherForecastGet.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const weatherForecastGetQueryKey = () => [{ url: '/api/WeatherForecast' }] as const

export type WeatherForecastGetQueryKey = ReturnType<typeof weatherForecastGetQueryKey>

/**
 * {@link /api/WeatherForecast}
 */
export async function weatherForecastGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<WeatherForecastGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/WeatherForecast`,
    ...requestConfig,
  })
  return res.data
}

export function weatherForecastGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = weatherForecastGetQueryKey()
  return queryOptions<WeatherForecastGetQueryResponse, ResponseErrorConfig<Error>, WeatherForecastGetQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return weatherForecastGet(config)
    },
  })
}

/**
 * {@link /api/WeatherForecast}
 */
export function useWeatherForecastGet<
  TData = WeatherForecastGetQueryResponse,
  TQueryData = WeatherForecastGetQueryResponse,
  TQueryKey extends QueryKey = WeatherForecastGetQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<WeatherForecastGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? weatherForecastGetQueryKey()

  const query = useQuery(
    {
      ...weatherForecastGetQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}