// <auto-generated />
using System;
using Ludus.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ludus.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Ludus.Shared.AgeRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long>("Category")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "checksum");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Rating")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<long>("RatingCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RatingCategoryId");

                    b.ToTable("AgeRating");

                    b.HasAnnotation("Relational:JsonPropertyName", "age_ratings");
                });

            modelBuilder.Entity("Ludus.Shared.AlternativeName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "checksum");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "comment");

                    b.Property<long>("Game")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "game");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("AlternativeName");

                    b.HasAnnotation("Relational:JsonPropertyName", "alternative_names");
                });

            modelBuilder.Entity("Ludus.Shared.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Collection");

                    b.HasAnnotation("Relational:JsonPropertyName", "collections");
                });

            modelBuilder.Entity("Ludus.Shared.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long>("LogoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.HasKey("Id");

                    b.HasIndex("LogoId");

                    b.ToTable("Company");

                    b.HasAnnotation("Relational:JsonPropertyName", "company");
                });

            modelBuilder.Entity("Ludus.Shared.Cover", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "image_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Cover");

                    b.HasAnnotation("Relational:JsonPropertyName", "cover");
                });

            modelBuilder.Entity("Ludus.Shared.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "checksum");

                    b.Property<long>("CoverId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<long>("FirstReleaseDate")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "first_release_date");

                    b.Property<long>("GameTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Hypes")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hypes");

                    b.PrimitiveCollection<string>("MultiplayerModes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "multiplayer_modes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<long>("RatingCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rating_count");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "summary");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.Property<double>("TotalRating")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "total_rating");

                    b.Property<long>("TotalRatingCount")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "total_rating_count");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.HasIndex("CoverId");

                    b.HasIndex("GameTypeId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Ludus.Shared.GameEngine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "checksum");

                    b.PrimitiveCollection<string>("Companies")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "companies");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.PrimitiveCollection<string>("Platforms")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "platforms");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameEngine");

                    b.HasAnnotation("Relational:JsonPropertyName", "game_engines");
                });

            modelBuilder.Entity("Ludus.Shared.GameLocalization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<long>("Region")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "region");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameLocalization");

                    b.HasAnnotation("Relational:JsonPropertyName", "game_localizations");
                });

            modelBuilder.Entity("Ludus.Shared.GameMode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GameId1")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GameId2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId1");

                    b.HasIndex("GameId2");

                    b.ToTable("GameMode");

                    b.HasAnnotation("Relational:JsonPropertyName", "language");
                });

            modelBuilder.Entity("Ludus.Shared.GameType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("GameType");

                    b.HasAnnotation("Relational:JsonPropertyName", "game_type");
                });

            modelBuilder.Entity("Ludus.Shared.InvolvedCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Developer")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "developer");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Publisher")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "publisher");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GameId");

                    b.ToTable("InvolvedCompany");

                    b.HasAnnotation("Relational:JsonPropertyName", "involved_companies");
                });

            modelBuilder.Entity("Ludus.Shared.LanguageSupport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageSupport");

                    b.HasAnnotation("Relational:JsonPropertyName", "language_supports");
                });

            modelBuilder.Entity("Ludus.Shared.Logo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<bool>("AlphaChannel")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "alpha_channel");

                    b.Property<bool>("Animated")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "animated");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "checksum");

                    b.Property<long>("Height")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "height");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "image_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.Property<long>("Width")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "width");

                    b.HasKey("Id");

                    b.ToTable("Logo");

                    b.HasAnnotation("Relational:JsonPropertyName", "logo");
                });

            modelBuilder.Entity("Ludus.Shared.LudusUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvatarImageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ludus.Shared.LudusUserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LudusUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LudusUserId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Ludus.Shared.Platform", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Platform");

                    b.HasAnnotation("Relational:JsonPropertyName", "platforms");
                });

            modelBuilder.Entity("Ludus.Shared.RatingCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.HasKey("Id");

                    b.ToTable("RatingCategory");

                    b.HasAnnotation("Relational:JsonPropertyName", "rating_category");
                });

            modelBuilder.Entity("Ludus.Shared.ReleaseDate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Platform")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("ReleaseDate");

                    b.HasAnnotation("Relational:JsonPropertyName", "release_dates");
                });

            modelBuilder.Entity("Ludus.Shared.SimilarGame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long>("Category")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<long>("CoverId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.HasKey("Id");

                    b.HasIndex("CoverId");

                    b.HasIndex("GameId");

                    b.ToTable("SimilarGame");

                    b.HasAnnotation("Relational:JsonPropertyName", "similar_games");
                });

            modelBuilder.Entity("Ludus.Shared.Theme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "checksum");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Theme");

                    b.HasAnnotation("Relational:JsonPropertyName", "themes");
                });

            modelBuilder.Entity("Ludus.Shared.Video", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "video_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Video");

                    b.HasAnnotation("Relational:JsonPropertyName", "videos");
                });

            modelBuilder.Entity("Ludus.Shared.Website", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long>("Category")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<long?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Website");

                    b.HasAnnotation("Relational:JsonPropertyName", "websites");
                });

            modelBuilder.Entity("Ludus.Shared.AgeRating", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("AgeRatings")
                        .HasForeignKey("GameId");

                    b.HasOne("Ludus.Shared.GameMode", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludus.Shared.RatingCategory", "RatingCategory")
                        .WithMany()
                        .HasForeignKey("RatingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("RatingCategory");
                });

            modelBuilder.Entity("Ludus.Shared.AlternativeName", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("AlternativeNames")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.Collection", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("Collections")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.Company", b =>
                {
                    b.HasOne("Ludus.Shared.Logo", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("Ludus.Shared.Cover", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("Screenshots")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.Game", b =>
                {
                    b.HasOne("Ludus.Shared.Cover", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludus.Shared.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cover");

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("Ludus.Shared.GameEngine", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("GameEngines")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.GameLocalization", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("GameLocalizations")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.GameMode", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("GameModes")
                        .HasForeignKey("GameId");

                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("Genres")
                        .HasForeignKey("GameId1");

                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("PlayerPerspectives")
                        .HasForeignKey("GameId2");
                });

            modelBuilder.Entity("Ludus.Shared.InvolvedCompany", b =>
                {
                    b.HasOne("Ludus.Shared.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("InvolvedCompanies")
                        .HasForeignKey("GameId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Ludus.Shared.LanguageSupport", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("LanguageSupports")
                        .HasForeignKey("GameId");

                    b.HasOne("Ludus.Shared.GameMode", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ludus.Shared.LudusUserImage", b =>
                {
                    b.HasOne("Ludus.Shared.LudusUser", "LudusUser")
                        .WithOne("LudusUserImage")
                        .HasForeignKey("Ludus.Shared.LudusUserImage", "LudusUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LudusUser");
                });

            modelBuilder.Entity("Ludus.Shared.Platform", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("Platforms")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.ReleaseDate", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("ReleaseDates")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.SimilarGame", b =>
                {
                    b.HasOne("Ludus.Shared.Cover", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("SimilarGames")
                        .HasForeignKey("GameId");

                    b.Navigation("Cover");
                });

            modelBuilder.Entity("Ludus.Shared.Theme", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("Themes")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.Video", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("Videos")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.Website", b =>
                {
                    b.HasOne("Ludus.Shared.Game", null)
                        .WithMany("Websites")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("Ludus.Shared.Game", b =>
                {
                    b.Navigation("AgeRatings");

                    b.Navigation("AlternativeNames");

                    b.Navigation("Collections");

                    b.Navigation("GameEngines");

                    b.Navigation("GameLocalizations");

                    b.Navigation("GameModes");

                    b.Navigation("Genres");

                    b.Navigation("InvolvedCompanies");

                    b.Navigation("LanguageSupports");

                    b.Navigation("Platforms");

                    b.Navigation("PlayerPerspectives");

                    b.Navigation("ReleaseDates");

                    b.Navigation("Screenshots");

                    b.Navigation("SimilarGames");

                    b.Navigation("Themes");

                    b.Navigation("Videos");

                    b.Navigation("Websites");
                });

            modelBuilder.Entity("Ludus.Shared.LudusUser", b =>
                {
                    b.Navigation("LudusUserImage");
                });
#pragma warning restore 612, 618
        }
    }
}
