/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Language = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  locale: string
}