/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetGamesByIdResponse } from './GetGamesByIdResponse.ts'

export type PublicGamesGetGameByIdEndpointPathParams = {
  /**
   * @type integer, int64
   */
  gameId: number
}

/**
 * @description Success
 */
export type PublicGamesGetGameByIdEndpoint200 = GetGamesByIdResponse

export type PublicGamesGetGameByIdEndpointQueryResponse = PublicGamesGetGameByIdEndpoint200

export type PublicGamesGetGameByIdEndpointQuery = {
  Response: PublicGamesGetGameByIdEndpoint200
  PathParams: PublicGamesGetGameByIdEndpointPathParams
  Errors: any
}