// <auto-generated/>
#pragma warning disable CS0618
using CatalogAPISDK.Catalog.Companies.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CatalogAPISDK.Catalog.Companies
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\companies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompaniesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the CatalogAPISDK.catalog.companies.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::CatalogAPISDK.Catalog.Companies.Item.WithCompanyItemRequestBuilder"/></returns>
        public global::CatalogAPISDK.Catalog.Companies.Item.WithCompanyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("companyId", position);
                return new global::CatalogAPISDK.Catalog.Companies.Item.WithCompanyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Catalog.Companies.CompaniesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompaniesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/companies", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Catalog.Companies.CompaniesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompaniesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/companies", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
