// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CatalogAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EventDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The endTimeUtc property</summary>
        public DateTimeOffset? EndTimeUtc { get; set; }
        /// <summary>The games property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CatalogAPISDK.Models.GameBrowseDto>? Games { get; set; }
#nullable restore
#else
        public List<global::CatalogAPISDK.Models.GameBrowseDto> Games { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The liveStreamUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LiveStreamUrl { get; set; }
#nullable restore
#else
        public string LiveStreamUrl { get; set; }
#endif
        /// <summary>The logoImageId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogoImageId { get; set; }
#nullable restore
#else
        public string LogoImageId { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The startTimeUtc property</summary>
        public DateTimeOffset? StartTimeUtc { get; set; }
        /// <summary>The timeZone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>The videos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CatalogAPISDK.Models.GameMediaVideoDto>? Videos { get; set; }
#nullable restore
#else
        public List<global::CatalogAPISDK.Models.GameMediaVideoDto> Videos { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Models.EventDto"/> and sets the default values.
        /// </summary>
        public EventDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CatalogAPISDK.Models.EventDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CatalogAPISDK.Models.EventDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CatalogAPISDK.Models.EventDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "endTimeUtc", n => { EndTimeUtc = n.GetDateTimeOffsetValue(); } },
                { "games", n => { Games = n.GetCollectionOfObjectValues<global::CatalogAPISDK.Models.GameBrowseDto>(global::CatalogAPISDK.Models.GameBrowseDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "liveStreamUrl", n => { LiveStreamUrl = n.GetStringValue(); } },
                { "logoImageId", n => { LogoImageId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "startTimeUtc", n => { StartTimeUtc = n.GetDateTimeOffsetValue(); } },
                { "timeZone", n => { TimeZone = n.GetStringValue(); } },
                { "videos", n => { Videos = n.GetCollectionOfObjectValues<global::CatalogAPISDK.Models.GameMediaVideoDto>(global::CatalogAPISDK.Models.GameMediaVideoDto.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("endTimeUtc", EndTimeUtc);
            writer.WriteCollectionOfObjectValues<global::CatalogAPISDK.Models.GameBrowseDto>("games", Games);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("liveStreamUrl", LiveStreamUrl);
            writer.WriteStringValue("logoImageId", LogoImageId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("slug", Slug);
            writer.WriteDateTimeOffsetValue("startTimeUtc", StartTimeUtc);
            writer.WriteStringValue("timeZone", TimeZone);
            writer.WriteCollectionOfObjectValues<global::CatalogAPISDK.Models.GameMediaVideoDto>("videos", Videos);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
