// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace CatalogAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GameBrowseDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The companies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CatalogAPISDK.Models.InvolvedCompanyDto>? Companies { get; set; }
#nullable restore
#else
        public List<global::CatalogAPISDK.Models.InvolvedCompanyDto> Companies { get; set; }
#endif
        /// <summary>The coverUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CoverUrl { get; set; }
#nullable restore
#else
        public string CoverUrl { get; set; }
#endif
        /// <summary>The firstReleaseDate property</summary>
        public Date? FirstReleaseDate { get; set; }
        /// <summary>The gameFeatures property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CatalogAPISDK.Models.GameFeatures? GameFeatures { get; set; }
#nullable restore
#else
        public global::CatalogAPISDK.Models.GameFeatures GameFeatures { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The platforms property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CatalogAPISDK.Models.PlatformDto>? Platforms { get; set; }
#nullable restore
#else
        public List<global::CatalogAPISDK.Models.PlatformDto> Platforms { get; set; }
#endif
        /// <summary>The steam property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CatalogAPISDK.Models.GameBrowseDto.GameBrowseDto_steam? Steam { get; set; }
#nullable restore
#else
        public global::CatalogAPISDK.Models.GameBrowseDto.GameBrowseDto_steam Steam { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Models.GameBrowseDto"/> and sets the default values.
        /// </summary>
        public GameBrowseDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CatalogAPISDK.Models.GameBrowseDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CatalogAPISDK.Models.GameBrowseDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::CatalogAPISDK.Models.GameBrowseDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "companies", n => { Companies = n.GetCollectionOfObjectValues<global::CatalogAPISDK.Models.InvolvedCompanyDto>(global::CatalogAPISDK.Models.InvolvedCompanyDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "coverUrl", n => { CoverUrl = n.GetStringValue(); } },
                { "firstReleaseDate", n => { FirstReleaseDate = n.GetDateValue(); } },
                { "gameFeatures", n => { GameFeatures = n.GetObjectValue<global::CatalogAPISDK.Models.GameFeatures>(global::CatalogAPISDK.Models.GameFeatures.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "platforms", n => { Platforms = n.GetCollectionOfObjectValues<global::CatalogAPISDK.Models.PlatformDto>(global::CatalogAPISDK.Models.PlatformDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "steam", n => { Steam = n.GetObjectValue<global::CatalogAPISDK.Models.GameBrowseDto.GameBrowseDto_steam>(global::CatalogAPISDK.Models.GameBrowseDto.GameBrowseDto_steam.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::CatalogAPISDK.Models.InvolvedCompanyDto>("companies", Companies);
            writer.WriteStringValue("coverUrl", CoverUrl);
            writer.WriteDateValue("firstReleaseDate", FirstReleaseDate);
            writer.WriteObjectValue<global::CatalogAPISDK.Models.GameFeatures>("gameFeatures", GameFeatures);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::CatalogAPISDK.Models.PlatformDto>("platforms", Platforms);
            writer.WriteObjectValue<global::CatalogAPISDK.Models.GameBrowseDto.GameBrowseDto_steam>("steam", Steam);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::CatalogAPISDK.Models.GameBrowseDto_steamMember1"/>, <see cref="global::CatalogAPISDK.Models.SteamData"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GameBrowseDto_steam : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::CatalogAPISDK.Models.GameBrowseDto_steamMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::CatalogAPISDK.Models.GameBrowseDto_steamMember1? GameBrowseDtoSteamMember1 { get; set; }
#nullable restore
#else
            public global::CatalogAPISDK.Models.GameBrowseDto_steamMember1 GameBrowseDtoSteamMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::CatalogAPISDK.Models.SteamData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::CatalogAPISDK.Models.SteamData? SteamData { get; set; }
#nullable restore
#else
            public global::CatalogAPISDK.Models.SteamData SteamData { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::CatalogAPISDK.Models.GameBrowseDto.GameBrowseDto_steam"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::CatalogAPISDK.Models.GameBrowseDto.GameBrowseDto_steam CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::CatalogAPISDK.Models.GameBrowseDto.GameBrowseDto_steam();
                if("SteamData".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.SteamData = new global::CatalogAPISDK.Models.SteamData();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GameBrowseDtoSteamMember1 != null)
                {
                    return GameBrowseDtoSteamMember1.GetFieldDeserializers();
                }
                else if(SteamData != null)
                {
                    return SteamData.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GameBrowseDtoSteamMember1 != null)
                {
                    writer.WriteObjectValue<global::CatalogAPISDK.Models.GameBrowseDto_steamMember1>(null, GameBrowseDtoSteamMember1);
                }
                else if(SteamData != null)
                {
                    writer.WriteObjectValue<global::CatalogAPISDK.Models.SteamData>(null, SteamData);
                }
            }
        }
    }
}
#pragma warning restore CS0618
