// <auto-generated/>
#pragma warning disable CS0618
using CatalogAPISDK.Api.Me.Wishlist.Games.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CatalogAPISDK.Api.Me.Wishlist.Games
{
    /// <summary>
    /// Builds and executes requests for operations under \api\me\wishlist\games
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GamesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the CatalogAPISDK.api.me.wishlist.games.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::CatalogAPISDK.Api.Me.Wishlist.Games.Item.WithGameItemRequestBuilder"/></returns>
        public global::CatalogAPISDK.Api.Me.Wishlist.Games.Item.WithGameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("gameId", position);
                return new global::CatalogAPISDK.Api.Me.Wishlist.Games.Item.WithGameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Api.Me.Wishlist.Games.GamesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/me/wishlist/games", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Api.Me.Wishlist.Games.GamesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GamesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/me/wishlist/games", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
