// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PlayAPISDK.Auth.Logout;
using PlayAPISDK.Auth.Me;
using PlayAPISDK.Auth.Mobile;
using PlayAPISDK.Auth.Steam;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PlayAPISDK.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The logout property</summary>
        public global::PlayAPISDK.Auth.Logout.LogoutRequestBuilder Logout
        {
            get => new global::PlayAPISDK.Auth.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::PlayAPISDK.Auth.Me.MeRequestBuilder Me
        {
            get => new global::PlayAPISDK.Auth.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mobile property</summary>
        public global::PlayAPISDK.Auth.Mobile.MobileRequestBuilder Mobile
        {
            get => new global::PlayAPISDK.Auth.Mobile.MobileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The steam property</summary>
        public global::PlayAPISDK.Auth.Steam.SteamRequestBuilder Steam
        {
            get => new global::PlayAPISDK.Auth.Steam.SteamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
