/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateListRequest = {
  /**
   * @minLength 5
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type boolean
   */
  public: boolean
}