/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User.ts'

export type GameHype = {
  /**
   * @type string, guid
   */
  id: string
  /**
   * @type integer, int64
   */
  gameId: number
  /**
   * @type string, date-time
   */
  hypeAt: string
  /**
   * @type string, guid
   */
  userId: string
  /**
   * @type object
   */
  user: User
}