/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Logo } from './Logo.ts'

export type GameEngine = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type object
   */
  logo: Logo
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  slug: string
  /**
   * @type string
   */
  url: string
}