/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GameWebsite = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type string
   */
  url: string
  /**
   * @type integer, int64
   */
  type: number
}