/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AlternativeName } from './AlternativeName.ts'
import type { Language } from './Language.ts'

export type LanguageSupport = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type object
   */
  language: Language
  /**
   * @type object
   */
  language_support_type: AlternativeName
}