/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetails } from './ProblemDetails.ts'

export type MeListsUpdateEndpointPathParams = {
  /**
   * @type string, guid
   */
  listId: string
}

export type MeListsUpdateEndpointQueryParams = {
  /**
   * @type string
   */
  name: string
  /**
   * @type boolean
   */
  public: boolean
}

/**
 * @description No Content
 */
export type MeListsUpdateEndpoint204 = any

/**
 * @description Bad Request
 */
export type MeListsUpdateEndpoint400 = ProblemDetails

/**
 * @description Unauthorized
 */
export type MeListsUpdateEndpoint401 = any

export type MeListsUpdateEndpointQueryResponse = MeListsUpdateEndpoint204

export type MeListsUpdateEndpointQuery = {
  Response: MeListsUpdateEndpoint204
  PathParams: MeListsUpdateEndpointPathParams
  QueryParams: MeListsUpdateEndpointQueryParams
  Errors: MeListsUpdateEndpoint400 | MeListsUpdateEndpoint401
}