// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PlayAPISDK.Catalog.Igdb.MostAnticipated;
using PlayAPISDK.Catalog.Igdb.Popscore;
using PlayAPISDK.Catalog.Igdb.Stats;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PlayAPISDK.Catalog.Igdb
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\igdb
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IgdbRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mostAnticipated property</summary>
        public global::PlayAPISDK.Catalog.Igdb.MostAnticipated.MostAnticipatedRequestBuilder MostAnticipated
        {
            get => new global::PlayAPISDK.Catalog.Igdb.MostAnticipated.MostAnticipatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The popscore property</summary>
        public global::PlayAPISDK.Catalog.Igdb.Popscore.PopscoreRequestBuilder Popscore
        {
            get => new global::PlayAPISDK.Catalog.Igdb.Popscore.PopscoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::PlayAPISDK.Catalog.Igdb.Stats.StatsRequestBuilder Stats
        {
            get => new global::PlayAPISDK.Catalog.Igdb.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Igdb.IgdbRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IgdbRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/igdb", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Igdb.IgdbRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IgdbRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/igdb", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
