// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Ludus.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReleaseDate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date property</summary>
        public long? Date { get; set; }
        /// <summary>The date_format property</summary>
        public long? DateFormat { get; set; }
        /// <summary>The human property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Human { get; set; }
#nullable restore
#else
        public string Human { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The release_region property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ludus.Client.Models.ReleaseRegion? ReleaseRegion { get; set; }
#nullable restore
#else
        public global::Ludus.Client.Models.ReleaseRegion ReleaseRegion { get; set; }
#endif
        /// <summary>The status property</summary>
        public long? Status { get; set; }
        /// <summary>The y property</summary>
        public long? Y { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Ludus.Client.Models.ReleaseDate"/> and sets the default values.
        /// </summary>
        public ReleaseDate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Ludus.Client.Models.ReleaseDate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Ludus.Client.Models.ReleaseDate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Ludus.Client.Models.ReleaseDate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date", n => { Date = n.GetLongValue(); } },
                { "date_format", n => { DateFormat = n.GetLongValue(); } },
                { "human", n => { Human = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "release_region", n => { ReleaseRegion = n.GetObjectValue<global::Ludus.Client.Models.ReleaseRegion>(global::Ludus.Client.Models.ReleaseRegion.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetLongValue(); } },
                { "y", n => { Y = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("date", Date);
            writer.WriteLongValue("date_format", DateFormat);
            writer.WriteStringValue("human", Human);
            writer.WriteLongValue("id", Id);
            writer.WriteObjectValue<global::Ludus.Client.Models.ReleaseRegion>("release_region", ReleaseRegion);
            writer.WriteLongValue("status", Status);
            writer.WriteLongValue("y", Y);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
