/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AlternativeName } from './AlternativeName.ts'
import type { CompanyWebsite } from './CompanyWebsite.ts'

export type Company = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type integer, int64
   */
  country: number
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  slug: string
  /**
   * @type array
   */
  websites: CompanyWebsite[]
  /**
   * @type object
   */
  status: AlternativeName
}