/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const gameStatusEnum = {
  NotStarted: 0,
  InProgress: 1,
  Completed: 2,
  Abandoned: 3,
  None: 4,
} as const

export type GameStatusEnum = (typeof gameStatusEnum)[keyof typeof gameStatusEnum]

export type GameStatus = GameStatusEnum