/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Company } from './Company.ts'

export type InvolvedCompany = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type object
   */
  company: Company
  /**
   * @type boolean
   */
  developer: boolean
  /**
   * @type boolean
   */
  porting: boolean
  /**
   * @type boolean
   */
  publisher: boolean
  /**
   * @type boolean
   */
  supporting: boolean
}