/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TrackGameIdRequest } from './TrackGameIdRequest.ts'
import type { TrackGameStateResponse } from './TrackGameStateResponse.ts'

/**
 * @description Success
 */
export type MeCollectionsCreateEndpoint200 = TrackGameStateResponse

/**
 * @description Unauthorized
 */
export type MeCollectionsCreateEndpoint401 = any

export type MeCollectionsCreateEndpointMutationRequest = TrackGameIdRequest

export type MeCollectionsCreateEndpointMutationResponse = MeCollectionsCreateEndpoint200

export type MeCollectionsCreateEndpointMutation = {
  Response: MeCollectionsCreateEndpoint200
  Request: MeCollectionsCreateEndpointMutationRequest
  Errors: MeCollectionsCreateEndpoint401
}