/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetGameStateResponse } from './GetGameStateResponse.ts'

export type MeCollectionsGetEndpointPathParams = {
  /**
   * @type integer, int64
   */
  gameId: number
}

/**
 * @description Success
 */
export type MeCollectionsGetEndpoint200 = GetGameStateResponse

/**
 * @description Unauthorized
 */
export type MeCollectionsGetEndpoint401 = any

export type MeCollectionsGetEndpointQueryResponse = MeCollectionsGetEndpoint200

export type MeCollectionsGetEndpointQuery = {
  Response: MeCollectionsGetEndpoint200
  PathParams: MeCollectionsGetEndpointPathParams
  Errors: MeCollectionsGetEndpoint401
}