/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetWishlistedGamesResponse } from './GetWishlistedGamesResponse.ts'

/**
 * @description Success
 */
export type MeWishlistsGetAllEndpoint200 = GetWishlistedGamesResponse

/**
 * @description Unauthorized
 */
export type MeWishlistsGetAllEndpoint401 = any

export type MeWishlistsGetAllEndpointQueryResponse = MeWishlistsGetAllEndpoint200

export type MeWishlistsGetAllEndpointQuery = {
  Response: MeWishlistsGetAllEndpoint200
  Errors: MeWishlistsGetAllEndpoint401
}