/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Logo } from './Logo.ts'

export type Platform = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type string
   */
  abbreviation: string
  /**
   * @type integer, int64
   */
  generation?: number | null
  /**
   * @type string
   */
  name: string
  /**
   * @type object
   */
  platform_logo: Logo
  /**
   * @type string
   */
  slug: string
}