/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetTopRatedGamesResponse } from './GetTopRatedGamesResponse.ts'

export type PublicGamesGetTopRatedGamesEndpointQueryParams = {
  /**
   * @type integer, int32
   */
  pageSize: number
  /**
   * @type integer, int32
   */
  pageNumber: number
}

/**
 * @description Success
 */
export type PublicGamesGetTopRatedGamesEndpoint200 = GetTopRatedGamesResponse

export type PublicGamesGetTopRatedGamesEndpointQueryResponse = PublicGamesGetTopRatedGamesEndpoint200

export type PublicGamesGetTopRatedGamesEndpointQuery = {
  Response: PublicGamesGetTopRatedGamesEndpoint200
  QueryParams: PublicGamesGetTopRatedGamesEndpointQueryParams
  Errors: any
}