/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ReleaseRegion = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type string
   */
  region: string
}