/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GameDto } from './GameDto.ts'

export type UserGameListDto = {
  /**
   * @type string, guid
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type boolean
   */
  public: boolean
  /**
   * @type integer, int32
   */
  totalItems: number
  /**
   * @type array
   */
  items: GameDto[]
}