version: 2

models:
    - name: game
      description: "Model for IGDB game data"
      columns:
          - name: _dlt_id
            description: "DLT Load ID"
            tests:
                - unique
                - not_null
          - name: id
            description: "Unique game ID from IGDB"
            tests:
                - unique
                - not_null
          - name: name
            description: "Name of the game"
          - name: slug
            description: "A url-safe, unique, lower-case version of the name"
          - name: summary
            description: " 	A description of the game"
          - name: storyline
            description: "A short description of a games story"
          - name: url
            description: "The website address (URL) of the item"
          - name: game_type
            description: "The type of game"
          - name: first_release_date
            description: "The first release date for this game"
          - name: aggregated_rating
            description: "Rating based on external critic scores"
          - name: aggregated_rating_count
            description: "Number of external critic scores"
          - name: hypes
            description: "Number of follows a game gets before release"
          - name: rating
            description: "Average IGDB user rating"
          - name: rating_count
            description: "Total number of IGDB user ratings"
          - name: total_rating
            description: "Average rating based on both IGDB user and external critic scores"
          - name: total_rating_count
            description: "TTotal number of user and external critic scores"
          - name: cover_id
            description: "ID of the game's cover art"
          - name: cover_name
            description: "Name associated with the cover art"
          - name: cover_url
            description: "URL to the game's cover art image"

    - name: company
      description: "Model for IGDB game data"
      columns:
          - name: id
            description: "DLT Load ID"
            tests:
                - unique
                - not_null
          - name: name
            description: "Unique game ID from IGDB"
          - name: native_name
            description: "Unique game ID from IGDB"
          - name: locale
            description: "Unique game ID from IGDB"
