// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PlayAPISDK.Api.Cookies.Consent;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PlayAPISDK.Api.Cookies
{
    /// <summary>
    /// Builds and executes requests for operations under \api\cookies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CookiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The consent property</summary>
        public global::PlayAPISDK.Api.Cookies.Consent.ConsentRequestBuilder Consent
        {
            get => new global::PlayAPISDK.Api.Cookies.Consent.ConsentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Api.Cookies.CookiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CookiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cookies", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Api.Cookies.CookiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CookiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cookies", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
