/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { AuthLoginEndpointQueryResponse, AuthLoginEndpoint403 } from '../../types/AuthLoginEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const authLoginEndpointSuspenseQueryKey = () => [{ url: '/signin' }] as const

export type AuthLoginEndpointSuspenseQueryKey = ReturnType<typeof authLoginEndpointSuspenseQueryKey>

/**
 * {@link /signin}
 */
export async function authLoginEndpointSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<AuthLoginEndpointQueryResponse, ResponseErrorConfig<AuthLoginEndpoint403>, unknown>({
    method: 'GET',
    url: `/signin`,
    ...requestConfig,
  })
  return res.data
}

export function authLoginEndpointSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = authLoginEndpointSuspenseQueryKey()
  return queryOptions<AuthLoginEndpointQueryResponse, ResponseErrorConfig<AuthLoginEndpoint403>, AuthLoginEndpointQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return authLoginEndpointSuspense(config)
    },
  })
}

/**
 * {@link /signin}
 */
export function useAuthLoginEndpointSuspense<TData = AuthLoginEndpointQueryResponse, TQueryKey extends QueryKey = AuthLoginEndpointSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<AuthLoginEndpointQueryResponse, ResponseErrorConfig<AuthLoginEndpoint403>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? authLoginEndpointSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...authLoginEndpointSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<AuthLoginEndpoint403>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}