// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using PlayAPISDK.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace PlayAPISDK.Catalog.Steam.Chart
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\steam\chart
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChartRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChartRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/steam/chart{?Page*,PageSize*,Type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChartRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/steam/chart{?Page*,PageSize*,Type*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::PlayAPISDK.Models.PagedGamesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::PlayAPISDK.Models.PagedGamesResponse?> GetAsync(Action<RequestConfiguration<global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder.ChartRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::PlayAPISDK.Models.PagedGamesResponse> GetAsync(Action<RequestConfiguration<global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder.ChartRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::PlayAPISDK.Models.PagedGamesResponse>(requestInfo, global::PlayAPISDK.Models.PagedGamesResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder.ChartRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder.ChartRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder WithUrl(string rawUrl)
        {
            return new global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ChartRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            public int? Page { get; set; }
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Type { get; set; }
#nullable restore
#else
            public string Type { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChartRequestBuilderGetRequestConfiguration : RequestConfiguration<global::PlayAPISDK.Catalog.Steam.Chart.ChartRequestBuilder.ChartRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
