// <auto-generated/>
#pragma warning disable CS0618
using Ludus.Client.Api.List.Item.Delete.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ludus.Client.Api.List.Item.Delete
{
    /// <summary>
    /// Builds and executes requests for operations under \api\list\{listId}\delete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Ludus.Client.api.list.item.delete.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Ludus.Client.Api.List.Item.Delete.Item.WithGameItemRequestBuilder"/></returns>
        public global::Ludus.Client.Api.List.Item.Delete.Item.WithGameItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("gameId", position);
                return new global::Ludus.Client.Api.List.Item.Delete.Item.WithGameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Ludus.Client.api.list.item.delete.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Ludus.Client.Api.List.Item.Delete.Item.WithGameItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Ludus.Client.Api.List.Item.Delete.Item.WithGameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("gameId", position);
                return new global::Ludus.Client.Api.List.Item.Delete.Item.WithGameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ludus.Client.Api.List.Item.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/list/{listId}/delete", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ludus.Client.Api.List.Item.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/list/{listId}/delete", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
