/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { AuthLoginEndpointQueryResponse, AuthLoginEndpoint403 } from '../../types/AuthLoginEndpoint.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const authLoginEndpointInfiniteQueryKey = () => [{ url: '/signin' }] as const

export type AuthLoginEndpointInfiniteQueryKey = ReturnType<typeof authLoginEndpointInfiniteQueryKey>

/**
 * {@link /signin}
 */
export async function authLoginEndpointInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<AuthLoginEndpointQueryResponse, ResponseErrorConfig<AuthLoginEndpoint403>, unknown>({
    method: 'GET',
    url: `/signin`,
    ...requestConfig,
  })
  return res
}

export function authLoginEndpointInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = authLoginEndpointInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<AuthLoginEndpointQueryResponse>,
    ResponseErrorConfig<AuthLoginEndpoint403>,
    ResponseConfig<AuthLoginEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return authLoginEndpointInfinite(config)
    },
    initialPageParam: 1,
    getNextPageParam: (lastPage) => lastPage['pageNumber'],
    getPreviousPageParam: (firstPage) => firstPage['pageNumber'],
  })
}

/**
 * {@link /signin}
 */
export function useAuthLoginEndpointInfinite<
  TData = InfiniteData<ResponseConfig<AuthLoginEndpointQueryResponse>>,
  TQueryData = ResponseConfig<AuthLoginEndpointQueryResponse>,
  TQueryKey extends QueryKey = AuthLoginEndpointInfiniteQueryKey,
>(
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<ResponseConfig<AuthLoginEndpointQueryResponse>, ResponseErrorConfig<AuthLoginEndpoint403>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? authLoginEndpointInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(authLoginEndpointInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<AuthLoginEndpoint403>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}