// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PlayAPISDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetGameMetricResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The firstVisitedAt property</summary>
        public DateTimeOffset? FirstVisitedAt { get; set; }
        /// <summary>The gameId property</summary>
        public long? GameId { get; set; }
        /// <summary>The lastVisitedAt property</summary>
        public DateTimeOffset? LastVisitedAt { get; set; }
        /// <summary>The sessionId property</summary>
        public Guid? SessionId { get; set; }
        /// <summary>The viewCount property</summary>
        public int? ViewCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Models.GetGameMetricResponse"/> and sets the default values.
        /// </summary>
        public GetGameMetricResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PlayAPISDK.Models.GetGameMetricResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PlayAPISDK.Models.GetGameMetricResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::PlayAPISDK.Models.GetGameMetricResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "firstVisitedAt", n => { FirstVisitedAt = n.GetDateTimeOffsetValue(); } },
                { "gameId", n => { GameId = n.GetLongValue(); } },
                { "lastVisitedAt", n => { LastVisitedAt = n.GetDateTimeOffsetValue(); } },
                { "sessionId", n => { SessionId = n.GetGuidValue(); } },
                { "viewCount", n => { ViewCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("firstVisitedAt", FirstVisitedAt);
            writer.WriteLongValue("gameId", GameId);
            writer.WriteDateTimeOffsetValue("lastVisitedAt", LastVisitedAt);
            writer.WriteGuidValue("sessionId", SessionId);
            writer.WriteIntValue("viewCount", ViewCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
