/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type {
  PublicGamesGetSimilarGamesEndpointQueryResponse,
  PublicGamesGetSimilarGamesEndpointPathParams,
} from '../../types/PublicGamesGetSimilarGamesEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const publicGamesGetSimilarGamesEndpointSuspenseQueryKey = (gameId: PublicGamesGetSimilarGamesEndpointPathParams['gameId']) =>
  [{ url: '/api/games/similar-games/:gameId', params: { gameId: gameId } }] as const

export type PublicGamesGetSimilarGamesEndpointSuspenseQueryKey = ReturnType<typeof publicGamesGetSimilarGamesEndpointSuspenseQueryKey>

/**
 * {@link /api/games/similar-games/:gameId}
 */
export async function publicGamesGetSimilarGamesEndpointSuspense(
  gameId: PublicGamesGetSimilarGamesEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<PublicGamesGetSimilarGamesEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/games/similar-games/${gameId}`,
    ...requestConfig,
  })
  return res.data
}

export function publicGamesGetSimilarGamesEndpointSuspenseQueryOptions(
  gameId: PublicGamesGetSimilarGamesEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = publicGamesGetSimilarGamesEndpointSuspenseQueryKey(gameId)
  return queryOptions<
    PublicGamesGetSimilarGamesEndpointQueryResponse,
    ResponseErrorConfig<Error>,
    PublicGamesGetSimilarGamesEndpointQueryResponse,
    typeof queryKey
  >({
    enabled: !!gameId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return publicGamesGetSimilarGamesEndpointSuspense(gameId, config)
    },
  })
}

/**
 * {@link /api/games/similar-games/:gameId}
 */
export function usePublicGamesGetSimilarGamesEndpointSuspense<
  TData = PublicGamesGetSimilarGamesEndpointQueryResponse,
  TQueryKey extends QueryKey = PublicGamesGetSimilarGamesEndpointSuspenseQueryKey,
>(
  gameId: PublicGamesGetSimilarGamesEndpointPathParams['gameId'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<PublicGamesGetSimilarGamesEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? publicGamesGetSimilarGamesEndpointSuspenseQueryKey(gameId)

  const query = useSuspenseQuery(
    {
      ...publicGamesGetSimilarGamesEndpointSuspenseQueryOptions(gameId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}