/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type {
  PublicGamesGetGamesByParametersEndpointMutationRequest,
  PublicGamesGetGamesByParametersEndpointMutationResponse,
} from '../../types/PublicGamesGetGamesByParametersEndpoint.ts'
import { useMutation } from '@tanstack/react-query'

export const publicGamesGetGamesByParametersEndpointMutationKey = () => [{ url: '/api/games/search' }] as const

export type PublicGamesGetGamesByParametersEndpointMutationKey = ReturnType<typeof publicGamesGetGamesByParametersEndpointMutationKey>

/**
 * {@link /api/games/search}
 */
export async function publicGamesGetGamesByParametersEndpoint(
  data: PublicGamesGetGamesByParametersEndpointMutationRequest,
  config: Partial<RequestConfig<PublicGamesGetGamesByParametersEndpointMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const res = await request<
    PublicGamesGetGamesByParametersEndpointMutationResponse,
    ResponseErrorConfig<Error>,
    PublicGamesGetGamesByParametersEndpointMutationRequest
  >({ method: 'POST', url: `/api/games/search`, data: requestData, ...requestConfig })
  return res.data
}

/**
 * {@link /api/games/search}
 */
export function usePublicGamesGetGamesByParametersEndpoint<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PublicGamesGetGamesByParametersEndpointMutationResponse,
      ResponseErrorConfig<Error>,
      { data: PublicGamesGetGamesByParametersEndpointMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PublicGamesGetGamesByParametersEndpointMutationRequest>> & { client?: typeof fetch }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? publicGamesGetGamesByParametersEndpointMutationKey()

  return useMutation<
    PublicGamesGetGamesByParametersEndpointMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PublicGamesGetGamesByParametersEndpointMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return publicGamesGetGamesByParametersEndpoint(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}