/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { PublicGamesGetGameByIdEndpointQueryResponse, PublicGamesGetGameByIdEndpointPathParams } from '../../types/PublicGamesGetGameByIdEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const publicGamesGetGameByIdEndpointSuspenseQueryKey = (gameId: PublicGamesGetGameByIdEndpointPathParams['gameId']) =>
  [{ url: '/api/games/:gameId', params: { gameId: gameId } }] as const

export type PublicGamesGetGameByIdEndpointSuspenseQueryKey = ReturnType<typeof publicGamesGetGameByIdEndpointSuspenseQueryKey>

/**
 * {@link /api/games/:gameId}
 */
export async function publicGamesGetGameByIdEndpointSuspense(
  gameId: PublicGamesGetGameByIdEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<PublicGamesGetGameByIdEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/games/${gameId}`,
    ...requestConfig,
  })
  return res.data
}

export function publicGamesGetGameByIdEndpointSuspenseQueryOptions(
  gameId: PublicGamesGetGameByIdEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = publicGamesGetGameByIdEndpointSuspenseQueryKey(gameId)
  return queryOptions<PublicGamesGetGameByIdEndpointQueryResponse, ResponseErrorConfig<Error>, PublicGamesGetGameByIdEndpointQueryResponse, typeof queryKey>({
    enabled: !!gameId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return publicGamesGetGameByIdEndpointSuspense(gameId, config)
    },
  })
}

/**
 * {@link /api/games/:gameId}
 */
export function usePublicGamesGetGameByIdEndpointSuspense<
  TData = PublicGamesGetGameByIdEndpointQueryResponse,
  TQueryKey extends QueryKey = PublicGamesGetGameByIdEndpointSuspenseQueryKey,
>(
  gameId: PublicGamesGetGameByIdEndpointPathParams['gameId'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<PublicGamesGetGameByIdEndpointQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? publicGamesGetGameByIdEndpointSuspenseQueryKey(gameId)

  const query = useSuspenseQuery(
    {
      ...publicGamesGetGameByIdEndpointSuspenseQueryOptions(gameId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}