/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { AuthLogoutEndpointQueryResponse, AuthLogoutEndpoint401, AuthLogoutEndpoint403 } from '../../types/AuthLogoutEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const authLogoutEndpointQueryKey = () => [{ url: '/signout' }] as const

export type AuthLogoutEndpointQueryKey = ReturnType<typeof authLogoutEndpointQueryKey>

/**
 * {@link /signout}
 */
export async function authLogoutEndpoint(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<AuthLogoutEndpointQueryResponse, ResponseErrorConfig<AuthLogoutEndpoint401 | AuthLogoutEndpoint403>, unknown>({
    method: 'GET',
    url: `/signout`,
    ...requestConfig,
  })
  return res
}

export function authLogoutEndpointQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = authLogoutEndpointQueryKey()
  return queryOptions<
    ResponseConfig<AuthLogoutEndpointQueryResponse>,
    ResponseErrorConfig<AuthLogoutEndpoint401 | AuthLogoutEndpoint403>,
    ResponseConfig<AuthLogoutEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return authLogoutEndpoint(config)
    },
  })
}

/**
 * {@link /signout}
 */
export function useAuthLogoutEndpoint<
  TData = ResponseConfig<AuthLogoutEndpointQueryResponse>,
  TQueryData = ResponseConfig<AuthLogoutEndpointQueryResponse>,
  TQueryKey extends QueryKey = AuthLogoutEndpointQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ResponseConfig<AuthLogoutEndpointQueryResponse>,
        ResponseErrorConfig<AuthLogoutEndpoint401 | AuthLogoutEndpoint403>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? authLogoutEndpointQueryKey()

  const query = useQuery(
    {
      ...(authLogoutEndpointQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<AuthLogoutEndpoint401 | AuthLogoutEndpoint403>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}