/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { PublicGamesGetFiltersEndpointQueryResponse } from '../../types/PublicGamesGetFiltersEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const publicGamesGetFiltersEndpointSuspenseQueryKey = () => [{ url: '/api/games/filters' }] as const

export type PublicGamesGetFiltersEndpointSuspenseQueryKey = ReturnType<typeof publicGamesGetFiltersEndpointSuspenseQueryKey>

/**
 * {@link /api/games/filters}
 */
export async function publicGamesGetFiltersEndpointSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PublicGamesGetFiltersEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/games/filters`,
    ...requestConfig,
  })
  return res
}

export function publicGamesGetFiltersEndpointSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = publicGamesGetFiltersEndpointSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<PublicGamesGetFiltersEndpointQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<PublicGamesGetFiltersEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return publicGamesGetFiltersEndpointSuspense(config)
    },
  })
}

/**
 * {@link /api/games/filters}
 */
export function usePublicGamesGetFiltersEndpointSuspense<
  TData = ResponseConfig<PublicGamesGetFiltersEndpointQueryResponse>,
  TQueryKey extends QueryKey = PublicGamesGetFiltersEndpointSuspenseQueryKey,
>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<PublicGamesGetFiltersEndpointQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? publicGamesGetFiltersEndpointSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(publicGamesGetFiltersEndpointSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}