/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type {
  PublicGamesGetSimilarGamesEndpointQueryResponse,
  PublicGamesGetSimilarGamesEndpointPathParams,
} from '../../types/PublicGamesGetSimilarGamesEndpoint.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const publicGamesGetSimilarGamesEndpointInfiniteQueryKey = (gameId: PublicGamesGetSimilarGamesEndpointPathParams['gameId']) =>
  [{ url: '/api/games/similar-games/:gameId', params: { gameId: gameId } }] as const

export type PublicGamesGetSimilarGamesEndpointInfiniteQueryKey = ReturnType<typeof publicGamesGetSimilarGamesEndpointInfiniteQueryKey>

/**
 * {@link /api/games/similar-games/:gameId}
 */
export async function publicGamesGetSimilarGamesEndpointInfinite(
  gameId: PublicGamesGetSimilarGamesEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PublicGamesGetSimilarGamesEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/games/similar-games/${gameId}`,
    ...requestConfig,
  })
  return res
}

export function publicGamesGetSimilarGamesEndpointInfiniteQueryOptions(
  gameId: PublicGamesGetSimilarGamesEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = publicGamesGetSimilarGamesEndpointInfiniteQueryKey(gameId)
  return infiniteQueryOptions<
    ResponseConfig<PublicGamesGetSimilarGamesEndpointQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<PublicGamesGetSimilarGamesEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!gameId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return publicGamesGetSimilarGamesEndpointInfinite(gameId, config)
    },
    initialPageParam: 1,
    getNextPageParam: (lastPage) => lastPage['pageNumber'],
    getPreviousPageParam: (firstPage) => firstPage['pageNumber'],
  })
}

/**
 * {@link /api/games/similar-games/:gameId}
 */
export function usePublicGamesGetSimilarGamesEndpointInfinite<
  TData = InfiniteData<ResponseConfig<PublicGamesGetSimilarGamesEndpointQueryResponse>>,
  TQueryData = ResponseConfig<PublicGamesGetSimilarGamesEndpointQueryResponse>,
  TQueryKey extends QueryKey = PublicGamesGetSimilarGamesEndpointInfiniteQueryKey,
>(
  gameId: PublicGamesGetSimilarGamesEndpointPathParams['gameId'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<ResponseConfig<PublicGamesGetSimilarGamesEndpointQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? publicGamesGetSimilarGamesEndpointInfiniteQueryKey(gameId)

  const query = useInfiniteQuery(
    {
      ...(publicGamesGetSimilarGamesEndpointInfiniteQueryOptions(gameId, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}