/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { PublicGamesGetGamesByIdEndpointQueryResponse, PublicGamesGetGamesByIdEndpointPathParams } from '../../types/PublicGamesGetGamesByIdEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const publicGamesGetGamesByIdEndpointQueryKey = (gameId: PublicGamesGetGamesByIdEndpointPathParams['gameId']) =>
  [{ url: '/api/games/:gameId', params: { gameId: gameId } }] as const

export type PublicGamesGetGamesByIdEndpointQueryKey = ReturnType<typeof publicGamesGetGamesByIdEndpointQueryKey>

/**
 * {@link /api/games/:gameId}
 */
export async function publicGamesGetGamesByIdEndpoint(
  gameId: PublicGamesGetGamesByIdEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PublicGamesGetGamesByIdEndpointQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/api/games/${gameId}`,
    ...requestConfig,
  })
  return res
}

export function publicGamesGetGamesByIdEndpointQueryOptions(
  gameId: PublicGamesGetGamesByIdEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = publicGamesGetGamesByIdEndpointQueryKey(gameId)
  return queryOptions<
    ResponseConfig<PublicGamesGetGamesByIdEndpointQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<PublicGamesGetGamesByIdEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!gameId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return publicGamesGetGamesByIdEndpoint(gameId, config)
    },
  })
}

/**
 * {@link /api/games/:gameId}
 */
export function usePublicGamesGetGamesByIdEndpoint<
  TData = ResponseConfig<PublicGamesGetGamesByIdEndpointQueryResponse>,
  TQueryData = ResponseConfig<PublicGamesGetGamesByIdEndpointQueryResponse>,
  TQueryKey extends QueryKey = PublicGamesGetGamesByIdEndpointQueryKey,
>(
  gameId: PublicGamesGetGamesByIdEndpointPathParams['gameId'],
  options: {
    query?: Partial<
      QueryObserverOptions<ResponseConfig<PublicGamesGetGamesByIdEndpointQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? publicGamesGetGamesByIdEndpointQueryKey(gameId)

  const query = useQuery(
    {
      ...(publicGamesGetGamesByIdEndpointQueryOptions(gameId, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}