/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type {
  PublicGamesGetGamesByIdsEndpointMutationRequest,
  PublicGamesGetGamesByIdsEndpointMutationResponse,
} from '../../types/PublicGamesGetGamesByIdsEndpoint.ts'
import { useMutation } from '@tanstack/react-query'

export const publicGamesGetGamesByIdsEndpointMutationKey = () => [{ url: '/api/games/by-ids' }] as const

export type PublicGamesGetGamesByIdsEndpointMutationKey = ReturnType<typeof publicGamesGetGamesByIdsEndpointMutationKey>

/**
 * {@link /api/games/by-ids}
 */
export async function publicGamesGetGamesByIdsEndpoint(
  data: PublicGamesGetGamesByIdsEndpointMutationRequest,
  config: Partial<RequestConfig<PublicGamesGetGamesByIdsEndpointMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PublicGamesGetGamesByIdsEndpointMutationResponse, ResponseErrorConfig<Error>, PublicGamesGetGamesByIdsEndpointMutationRequest>({
    method: 'POST',
    url: `/api/games/by-ids`,
    data,
    ...requestConfig,
  })
  return res
}

/**
 * {@link /api/games/by-ids}
 */
export function usePublicGamesGetGamesByIdsEndpoint<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PublicGamesGetGamesByIdsEndpointMutationResponse>,
      ResponseErrorConfig<Error>,
      { data: PublicGamesGetGamesByIdsEndpointMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PublicGamesGetGamesByIdsEndpointMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? publicGamesGetGamesByIdsEndpointMutationKey()

  return useMutation<
    ResponseConfig<PublicGamesGetGamesByIdsEndpointMutationResponse>,
    ResponseErrorConfig<Error>,
    { data: PublicGamesGetGamesByIdsEndpointMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return publicGamesGetGamesByIdsEndpoint(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}