/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { AuthSteamResponseEndpointQueryResponse, AuthSteamResponseEndpoint403 } from '../../types/AuthSteamResponseEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const authSteamResponseEndpointQueryKey = () => [{ url: '/Auth/steamresponse' }] as const

export type AuthSteamResponseEndpointQueryKey = ReturnType<typeof authSteamResponseEndpointQueryKey>

/**
 * {@link /Auth/steamresponse}
 */
export async function authSteamResponseEndpoint(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<AuthSteamResponseEndpointQueryResponse, ResponseErrorConfig<AuthSteamResponseEndpoint403>, unknown>({
    method: 'GET',
    url: `/Auth/steamresponse`,
    ...requestConfig,
  })
  return res
}

export function authSteamResponseEndpointQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = authSteamResponseEndpointQueryKey()
  return queryOptions<
    ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
    ResponseErrorConfig<AuthSteamResponseEndpoint403>,
    ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return authSteamResponseEndpoint(config)
    },
  })
}

/**
 * {@link /Auth/steamresponse}
 */
export function useAuthSteamResponseEndpoint<
  TData = ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
  TQueryData = ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
  TQueryKey extends QueryKey = AuthSteamResponseEndpointQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
        ResponseErrorConfig<AuthSteamResponseEndpoint403>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? authSteamResponseEndpointQueryKey()

  const query = useQuery(
    {
      ...(authSteamResponseEndpointQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<AuthSteamResponseEndpoint403>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}