/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { AuthSteamResponseEndpointQueryResponse, AuthSteamResponseEndpoint403 } from '../../types/AuthSteamResponseEndpoint.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const authSteamResponseEndpointInfiniteQueryKey = () => [{ url: '/Auth/steamresponse' }] as const

export type AuthSteamResponseEndpointInfiniteQueryKey = ReturnType<typeof authSteamResponseEndpointInfiniteQueryKey>

/**
 * {@link /Auth/steamresponse}
 */
export async function authSteamResponseEndpointInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<AuthSteamResponseEndpointQueryResponse, ResponseErrorConfig<AuthSteamResponseEndpoint403>, unknown>({
    method: 'GET',
    url: `/Auth/steamresponse`,
    ...requestConfig,
  })
  return res
}

export function authSteamResponseEndpointInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = authSteamResponseEndpointInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
    ResponseErrorConfig<AuthSteamResponseEndpoint403>,
    ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return authSteamResponseEndpointInfinite(config)
    },
    initialPageParam: 1,
    getNextPageParam: (lastPage) => lastPage['pageNumber'],
    getPreviousPageParam: (firstPage) => firstPage['pageNumber'],
  })
}

/**
 * {@link /Auth/steamresponse}
 */
export function useAuthSteamResponseEndpointInfinite<
  TData = InfiniteData<ResponseConfig<AuthSteamResponseEndpointQueryResponse>>,
  TQueryData = ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
  TQueryKey extends QueryKey = AuthSteamResponseEndpointInfiniteQueryKey,
>(
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<AuthSteamResponseEndpointQueryResponse>,
        ResponseErrorConfig<AuthSteamResponseEndpoint403>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? authSteamResponseEndpointInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(authSteamResponseEndpointInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<AuthSteamResponseEndpoint403>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}