/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { MeProfileGetEndpointQueryResponse, MeProfileGetEndpoint401 } from '../../types/MeProfileGetEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const meProfileGetEndpointSuspenseQueryKey = () => [{ url: '/api/me/profile/me' }] as const

export type MeProfileGetEndpointSuspenseQueryKey = ReturnType<typeof meProfileGetEndpointSuspenseQueryKey>

/**
 * {@link /api/me/profile/me}
 */
export async function meProfileGetEndpointSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeProfileGetEndpointQueryResponse, ResponseErrorConfig<MeProfileGetEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/profile/me`,
    ...requestConfig,
  })
  return res
}

export function meProfileGetEndpointSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = meProfileGetEndpointSuspenseQueryKey()
  return queryOptions<
    ResponseConfig<MeProfileGetEndpointQueryResponse>,
    ResponseErrorConfig<MeProfileGetEndpoint401>,
    ResponseConfig<MeProfileGetEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meProfileGetEndpointSuspense(config)
    },
  })
}

/**
 * {@link /api/me/profile/me}
 */
export function useMeProfileGetEndpointSuspense<
  TData = ResponseConfig<MeProfileGetEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeProfileGetEndpointSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<ResponseConfig<MeProfileGetEndpointQueryResponse>, ResponseErrorConfig<MeProfileGetEndpoint401>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meProfileGetEndpointSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(meProfileGetEndpointSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<MeProfileGetEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}