/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { MeListsGetEndpointQueryResponse, MeListsGetEndpointPathParams, MeListsGetEndpoint401 } from '../../types/MeListsGetEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const meListsGetEndpointSuspenseQueryKey = (listId: MeListsGetEndpointPathParams['listId']) =>
  [{ url: '/api/me/lists/:listId', params: { listId: listId } }] as const

export type MeListsGetEndpointSuspenseQueryKey = ReturnType<typeof meListsGetEndpointSuspenseQueryKey>

/**
 * {@link /api/me/lists/:listId}
 */
export async function meListsGetEndpointSuspense(
  listId: MeListsGetEndpointPathParams['listId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeListsGetEndpointQueryResponse, ResponseErrorConfig<MeListsGetEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/lists/${listId}`,
    ...requestConfig,
  })
  return res
}

export function meListsGetEndpointSuspenseQueryOptions(
  listId: MeListsGetEndpointPathParams['listId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = meListsGetEndpointSuspenseQueryKey(listId)
  return queryOptions<
    ResponseConfig<MeListsGetEndpointQueryResponse>,
    ResponseErrorConfig<MeListsGetEndpoint401>,
    ResponseConfig<MeListsGetEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!listId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meListsGetEndpointSuspense(listId, config)
    },
  })
}

/**
 * {@link /api/me/lists/:listId}
 */
export function useMeListsGetEndpointSuspense<
  TData = ResponseConfig<MeListsGetEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeListsGetEndpointSuspenseQueryKey,
>(
  listId: MeListsGetEndpointPathParams['listId'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<MeListsGetEndpointQueryResponse>, ResponseErrorConfig<MeListsGetEndpoint401>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meListsGetEndpointSuspenseQueryKey(listId)

  const query = useSuspenseQuery(
    {
      ...(meListsGetEndpointSuspenseQueryOptions(listId, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<MeListsGetEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}