/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type { MeListsItemAddEndpointQueryResponse, MeListsItemAddEndpointPathParams, MeListsItemAddEndpoint401 } from '../../types/MeListsItemAddEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const meListsItemAddEndpointSuspenseQueryKey = (
  listId: MeListsItemAddEndpointPathParams['listId'],
  gameId: MeListsItemAddEndpointPathParams['gameId'],
) => [{ url: '/api/me/lists/add/:listId/:gameId', params: { listId: listId, gameId: gameId } }] as const

export type MeListsItemAddEndpointSuspenseQueryKey = ReturnType<typeof meListsItemAddEndpointSuspenseQueryKey>

/**
 * {@link /api/me/lists/add/:listId/:gameId}
 */
export async function meListsItemAddEndpointSuspense(
  listId: MeListsItemAddEndpointPathParams['listId'],
  gameId: MeListsItemAddEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeListsItemAddEndpointQueryResponse, ResponseErrorConfig<MeListsItemAddEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/lists/add/${listId}/${gameId}`,
    ...requestConfig,
  })
  return res
}

export function meListsItemAddEndpointSuspenseQueryOptions(
  listId: MeListsItemAddEndpointPathParams['listId'],
  gameId: MeListsItemAddEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = meListsItemAddEndpointSuspenseQueryKey(listId, gameId)
  return queryOptions<
    ResponseConfig<MeListsItemAddEndpointQueryResponse>,
    ResponseErrorConfig<MeListsItemAddEndpoint401>,
    ResponseConfig<MeListsItemAddEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!(listId && gameId),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meListsItemAddEndpointSuspense(listId, gameId, config)
    },
  })
}

/**
 * {@link /api/me/lists/add/:listId/:gameId}
 */
export function useMeListsItemAddEndpointSuspense<
  TData = ResponseConfig<MeListsItemAddEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeListsItemAddEndpointSuspenseQueryKey,
>(
  listId: MeListsItemAddEndpointPathParams['listId'],
  gameId: MeListsItemAddEndpointPathParams['gameId'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<ResponseConfig<MeListsItemAddEndpointQueryResponse>, ResponseErrorConfig<MeListsItemAddEndpoint401>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meListsItemAddEndpointSuspenseQueryKey(listId, gameId)

  const query = useSuspenseQuery(
    {
      ...(meListsItemAddEndpointSuspenseQueryOptions(listId, gameId, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<MeListsItemAddEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}