/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type {
  MeFavoritesUpdateEndpointMutationRequest,
  MeFavoritesUpdateEndpointMutationResponse,
  MeFavoritesUpdateEndpointPathParams,
  MeFavoritesUpdateEndpoint401,
} from '../../types/MeFavoritesUpdateEndpoint.ts'
import { useMutation } from '@tanstack/react-query'

export const meFavoritesUpdateEndpointMutationKey = () => [{ url: '/api/me/favorites/update/{gameId}' }] as const

export type MeFavoritesUpdateEndpointMutationKey = ReturnType<typeof meFavoritesUpdateEndpointMutationKey>

/**
 * {@link /api/me/favorites/update/:gameId}
 */
export async function meFavoritesUpdateEndpoint(
  gameId: MeFavoritesUpdateEndpointPathParams['gameId'],
  data: MeFavoritesUpdateEndpointMutationRequest,
  config: Partial<RequestConfig<MeFavoritesUpdateEndpointMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    MeFavoritesUpdateEndpointMutationResponse,
    ResponseErrorConfig<MeFavoritesUpdateEndpoint401>,
    MeFavoritesUpdateEndpointMutationRequest
  >({ method: 'POST', url: `/api/me/favorites/update/${gameId}`, data, ...requestConfig })
  return res
}

/**
 * {@link /api/me/favorites/update/:gameId}
 */
export function useMeFavoritesUpdateEndpoint<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<MeFavoritesUpdateEndpointMutationResponse>,
      ResponseErrorConfig<MeFavoritesUpdateEndpoint401>,
      { gameId: MeFavoritesUpdateEndpointPathParams['gameId']; data: MeFavoritesUpdateEndpointMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<MeFavoritesUpdateEndpointMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? meFavoritesUpdateEndpointMutationKey()

  return useMutation<
    ResponseConfig<MeFavoritesUpdateEndpointMutationResponse>,
    ResponseErrorConfig<MeFavoritesUpdateEndpoint401>,
    { gameId: MeFavoritesUpdateEndpointPathParams['gameId']; data: MeFavoritesUpdateEndpointMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ gameId, data }) => {
        return meFavoritesUpdateEndpoint(gameId, data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}