/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type {
  MeListsUpdateEndpointQueryResponse,
  MeListsUpdateEndpointPathParams,
  MeListsUpdateEndpointQueryParams,
  MeListsUpdateEndpoint400,
  MeListsUpdateEndpoint401,
} from '../../types/MeListsUpdateEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const meListsUpdateEndpointSuspenseQueryKey = (listId: MeListsUpdateEndpointPathParams['listId'], params: MeListsUpdateEndpointQueryParams) =>
  [{ url: '/api/me/lists/update/:listId', params: { listId: listId } }, ...(params ? [params] : [])] as const

export type MeListsUpdateEndpointSuspenseQueryKey = ReturnType<typeof meListsUpdateEndpointSuspenseQueryKey>

/**
 * {@link /api/me/lists/update/:listId}
 */
export async function meListsUpdateEndpointSuspense(
  listId: MeListsUpdateEndpointPathParams['listId'],
  params: MeListsUpdateEndpointQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeListsUpdateEndpointQueryResponse, ResponseErrorConfig<MeListsUpdateEndpoint400 | MeListsUpdateEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/lists/update/${listId}`,
    params,
    ...requestConfig,
  })
  return res
}

export function meListsUpdateEndpointSuspenseQueryOptions(
  listId: MeListsUpdateEndpointPathParams['listId'],
  params: MeListsUpdateEndpointQueryParams,
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = meListsUpdateEndpointSuspenseQueryKey(listId, params)
  return queryOptions<
    ResponseConfig<MeListsUpdateEndpointQueryResponse>,
    ResponseErrorConfig<MeListsUpdateEndpoint400 | MeListsUpdateEndpoint401>,
    ResponseConfig<MeListsUpdateEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!(listId && params),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meListsUpdateEndpointSuspense(listId, params, config)
    },
  })
}

/**
 * {@link /api/me/lists/update/:listId}
 */
export function useMeListsUpdateEndpointSuspense<
  TData = ResponseConfig<MeListsUpdateEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeListsUpdateEndpointSuspenseQueryKey,
>(
  listId: MeListsUpdateEndpointPathParams['listId'],
  params: MeListsUpdateEndpointQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ResponseConfig<MeListsUpdateEndpointQueryResponse>,
        ResponseErrorConfig<MeListsUpdateEndpoint400 | MeListsUpdateEndpoint401>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meListsUpdateEndpointSuspenseQueryKey(listId, params)

  const query = useSuspenseQuery(
    {
      ...(meListsUpdateEndpointSuspenseQueryOptions(listId, params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<MeListsUpdateEndpoint400 | MeListsUpdateEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}