/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { MeFavoritesGetAllEndpointQueryResponse, MeFavoritesGetAllEndpoint401 } from '../../types/MeFavoritesGetAllEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const meFavoritesGetAllEndpointQueryKey = () => [{ url: '/api/me/favorites/all' }] as const

export type MeFavoritesGetAllEndpointQueryKey = ReturnType<typeof meFavoritesGetAllEndpointQueryKey>

/**
 * {@link /api/me/favorites/all}
 */
export async function meFavoritesGetAllEndpoint(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeFavoritesGetAllEndpointQueryResponse, ResponseErrorConfig<MeFavoritesGetAllEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/favorites/all`,
    ...requestConfig,
  })
  return res
}

export function meFavoritesGetAllEndpointQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = meFavoritesGetAllEndpointQueryKey()
  return queryOptions<
    ResponseConfig<MeFavoritesGetAllEndpointQueryResponse>,
    ResponseErrorConfig<MeFavoritesGetAllEndpoint401>,
    ResponseConfig<MeFavoritesGetAllEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meFavoritesGetAllEndpoint(config)
    },
  })
}

/**
 * {@link /api/me/favorites/all}
 */
export function useMeFavoritesGetAllEndpoint<
  TData = ResponseConfig<MeFavoritesGetAllEndpointQueryResponse>,
  TQueryData = ResponseConfig<MeFavoritesGetAllEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeFavoritesGetAllEndpointQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ResponseConfig<MeFavoritesGetAllEndpointQueryResponse>,
        ResponseErrorConfig<MeFavoritesGetAllEndpoint401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meFavoritesGetAllEndpointQueryKey()

  const query = useQuery(
    {
      ...(meFavoritesGetAllEndpointQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<MeFavoritesGetAllEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}