/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type {
  MeCollectionsCreateEndpointMutationRequest,
  MeCollectionsCreateEndpointMutationResponse,
  MeCollectionsCreateEndpoint401,
} from '../../types/MeCollectionsCreateEndpoint.ts'
import { useMutation } from '@tanstack/react-query'

export const meCollectionsCreateEndpointMutationKey = () => [{ url: '/api/me/collections/create' }] as const

export type MeCollectionsCreateEndpointMutationKey = ReturnType<typeof meCollectionsCreateEndpointMutationKey>

/**
 * {@link /api/me/collections/create}
 */
export async function meCollectionsCreateEndpoint(
  data: MeCollectionsCreateEndpointMutationRequest,
  config: Partial<RequestConfig<MeCollectionsCreateEndpointMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    MeCollectionsCreateEndpointMutationResponse,
    ResponseErrorConfig<MeCollectionsCreateEndpoint401>,
    MeCollectionsCreateEndpointMutationRequest
  >({ method: 'POST', url: `/api/me/collections/create`, data, ...requestConfig })
  return res
}

/**
 * {@link /api/me/collections/create}
 */
export function useMeCollectionsCreateEndpoint<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<MeCollectionsCreateEndpointMutationResponse>,
      ResponseErrorConfig<MeCollectionsCreateEndpoint401>,
      { data: MeCollectionsCreateEndpointMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<MeCollectionsCreateEndpointMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? meCollectionsCreateEndpointMutationKey()

  return useMutation<
    ResponseConfig<MeCollectionsCreateEndpointMutationResponse>,
    ResponseErrorConfig<MeCollectionsCreateEndpoint401>,
    { data: MeCollectionsCreateEndpointMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return meCollectionsCreateEndpoint(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}