/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type {
  MeListsItemRemoveEndpointQueryResponse,
  MeListsItemRemoveEndpointPathParams,
  MeListsItemRemoveEndpoint401,
} from '../../types/MeListsItemRemoveEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const meListsItemRemoveEndpointQueryKey = (
  listId: MeListsItemRemoveEndpointPathParams['listId'],
  gameId: MeListsItemRemoveEndpointPathParams['gameId'],
) => [{ url: '/api/me/lists/remove/:listId/:gameId', params: { listId: listId, gameId: gameId } }] as const

export type MeListsItemRemoveEndpointQueryKey = ReturnType<typeof meListsItemRemoveEndpointQueryKey>

/**
 * {@link /api/me/lists/remove/:listId/:gameId}
 */
export async function meListsItemRemoveEndpoint(
  listId: MeListsItemRemoveEndpointPathParams['listId'],
  gameId: MeListsItemRemoveEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeListsItemRemoveEndpointQueryResponse, ResponseErrorConfig<MeListsItemRemoveEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/lists/remove/${listId}/${gameId}`,
    ...requestConfig,
  })
  return res
}

export function meListsItemRemoveEndpointQueryOptions(
  listId: MeListsItemRemoveEndpointPathParams['listId'],
  gameId: MeListsItemRemoveEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = meListsItemRemoveEndpointQueryKey(listId, gameId)
  return queryOptions<
    ResponseConfig<MeListsItemRemoveEndpointQueryResponse>,
    ResponseErrorConfig<MeListsItemRemoveEndpoint401>,
    ResponseConfig<MeListsItemRemoveEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!(listId && gameId),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meListsItemRemoveEndpoint(listId, gameId, config)
    },
  })
}

/**
 * {@link /api/me/lists/remove/:listId/:gameId}
 */
export function useMeListsItemRemoveEndpoint<
  TData = ResponseConfig<MeListsItemRemoveEndpointQueryResponse>,
  TQueryData = ResponseConfig<MeListsItemRemoveEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeListsItemRemoveEndpointQueryKey,
>(
  listId: MeListsItemRemoveEndpointPathParams['listId'],
  gameId: MeListsItemRemoveEndpointPathParams['gameId'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        ResponseConfig<MeListsItemRemoveEndpointQueryResponse>,
        ResponseErrorConfig<MeListsItemRemoveEndpoint401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meListsItemRemoveEndpointQueryKey(listId, gameId)

  const query = useQuery(
    {
      ...(meListsItemRemoveEndpointQueryOptions(listId, gameId, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<MeListsItemRemoveEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}