/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { MeProfileGetEndpointQueryResponse, MeProfileGetEndpoint401 } from '../../types/MeProfileGetEndpoint.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const meProfileGetEndpointInfiniteQueryKey = () => [{ url: '/api/me/profile/me' }] as const

export type MeProfileGetEndpointInfiniteQueryKey = ReturnType<typeof meProfileGetEndpointInfiniteQueryKey>

/**
 * {@link /api/me/profile/me}
 */
export async function meProfileGetEndpointInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeProfileGetEndpointQueryResponse, ResponseErrorConfig<MeProfileGetEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/profile/me`,
    ...requestConfig,
  })
  return res
}

export function meProfileGetEndpointInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = meProfileGetEndpointInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<MeProfileGetEndpointQueryResponse>,
    ResponseErrorConfig<MeProfileGetEndpoint401>,
    ResponseConfig<MeProfileGetEndpointQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meProfileGetEndpointInfinite(config)
    },
    initialPageParam: 1,
    getNextPageParam: (lastPage) => lastPage['pageNumber'],
    getPreviousPageParam: (firstPage) => firstPage['pageNumber'],
  })
}

/**
 * {@link /api/me/profile/me}
 */
export function useMeProfileGetEndpointInfinite<
  TData = InfiniteData<ResponseConfig<MeProfileGetEndpointQueryResponse>>,
  TQueryData = ResponseConfig<MeProfileGetEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeProfileGetEndpointInfiniteQueryKey,
>(
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<MeProfileGetEndpointQueryResponse>,
        ResponseErrorConfig<MeProfileGetEndpoint401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meProfileGetEndpointInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(meProfileGetEndpointInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<MeProfileGetEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}