/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type {
  MeCollectionsGetEndpointQueryResponse,
  MeCollectionsGetEndpointPathParams,
  MeCollectionsGetEndpoint401,
} from '../../types/MeCollectionsGetEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const meCollectionsGetEndpointQueryKey = (gameId: MeCollectionsGetEndpointPathParams['gameId']) =>
  [{ url: '/api/me/collections/:gameId', params: { gameId: gameId } }] as const

export type MeCollectionsGetEndpointQueryKey = ReturnType<typeof meCollectionsGetEndpointQueryKey>

/**
 * {@link /api/me/collections/:gameId}
 */
export async function meCollectionsGetEndpoint(
  gameId: MeCollectionsGetEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeCollectionsGetEndpointQueryResponse, ResponseErrorConfig<MeCollectionsGetEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/collections/${gameId}`,
    ...requestConfig,
  })
  return res
}

export function meCollectionsGetEndpointQueryOptions(
  gameId: MeCollectionsGetEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = meCollectionsGetEndpointQueryKey(gameId)
  return queryOptions<
    ResponseConfig<MeCollectionsGetEndpointQueryResponse>,
    ResponseErrorConfig<MeCollectionsGetEndpoint401>,
    ResponseConfig<MeCollectionsGetEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!gameId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meCollectionsGetEndpoint(gameId, config)
    },
  })
}

/**
 * {@link /api/me/collections/:gameId}
 */
export function useMeCollectionsGetEndpoint<
  TData = ResponseConfig<MeCollectionsGetEndpointQueryResponse>,
  TQueryData = ResponseConfig<MeCollectionsGetEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeCollectionsGetEndpointQueryKey,
>(
  gameId: MeCollectionsGetEndpointPathParams['gameId'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        ResponseConfig<MeCollectionsGetEndpointQueryResponse>,
        ResponseErrorConfig<MeCollectionsGetEndpoint401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meCollectionsGetEndpointQueryKey(gameId)

  const query = useQuery(
    {
      ...(meCollectionsGetEndpointQueryOptions(gameId, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<MeCollectionsGetEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}