/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type {
  MeCollectionsGetEndpointQueryResponse,
  MeCollectionsGetEndpointPathParams,
  MeCollectionsGetEndpoint401,
} from '../../types/MeCollectionsGetEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const meCollectionsGetEndpointSuspenseQueryKey = (gameId: MeCollectionsGetEndpointPathParams['gameId']) =>
  [{ url: '/api/me/collections/:gameId', params: { gameId: gameId } }] as const

export type MeCollectionsGetEndpointSuspenseQueryKey = ReturnType<typeof meCollectionsGetEndpointSuspenseQueryKey>

/**
 * {@link /api/me/collections/:gameId}
 */
export async function meCollectionsGetEndpointSuspense(
  gameId: MeCollectionsGetEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeCollectionsGetEndpointQueryResponse, ResponseErrorConfig<MeCollectionsGetEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/collections/${gameId}`,
    ...requestConfig,
  })
  return res
}

export function meCollectionsGetEndpointSuspenseQueryOptions(
  gameId: MeCollectionsGetEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = meCollectionsGetEndpointSuspenseQueryKey(gameId)
  return queryOptions<
    ResponseConfig<MeCollectionsGetEndpointQueryResponse>,
    ResponseErrorConfig<MeCollectionsGetEndpoint401>,
    ResponseConfig<MeCollectionsGetEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!gameId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meCollectionsGetEndpointSuspense(gameId, config)
    },
  })
}

/**
 * {@link /api/me/collections/:gameId}
 */
export function useMeCollectionsGetEndpointSuspense<
  TData = ResponseConfig<MeCollectionsGetEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeCollectionsGetEndpointSuspenseQueryKey,
>(
  gameId: MeCollectionsGetEndpointPathParams['gameId'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<ResponseConfig<MeCollectionsGetEndpointQueryResponse>, ResponseErrorConfig<MeCollectionsGetEndpoint401>, TData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meCollectionsGetEndpointSuspenseQueryKey(gameId)

  const query = useSuspenseQuery(
    {
      ...(meCollectionsGetEndpointSuspenseQueryOptions(gameId, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<MeCollectionsGetEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}