/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import type { MeListsItemAddEndpointQueryResponse, MeListsItemAddEndpointPathParams, MeListsItemAddEndpoint401 } from '../../types/MeListsItemAddEndpoint.ts'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const meListsItemAddEndpointInfiniteQueryKey = (
  listId: MeListsItemAddEndpointPathParams['listId'],
  gameId: MeListsItemAddEndpointPathParams['gameId'],
) => [{ url: '/api/me/lists/add/:listId/:gameId', params: { listId: listId, gameId: gameId } }] as const

export type MeListsItemAddEndpointInfiniteQueryKey = ReturnType<typeof meListsItemAddEndpointInfiniteQueryKey>

/**
 * {@link /api/me/lists/add/:listId/:gameId}
 */
export async function meListsItemAddEndpointInfinite(
  listId: MeListsItemAddEndpointPathParams['listId'],
  gameId: MeListsItemAddEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<MeListsItemAddEndpointQueryResponse, ResponseErrorConfig<MeListsItemAddEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/lists/add/${listId}/${gameId}`,
    ...requestConfig,
  })
  return res
}

export function meListsItemAddEndpointInfiniteQueryOptions(
  listId: MeListsItemAddEndpointPathParams['listId'],
  gameId: MeListsItemAddEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = meListsItemAddEndpointInfiniteQueryKey(listId, gameId)
  return infiniteQueryOptions<
    ResponseConfig<MeListsItemAddEndpointQueryResponse>,
    ResponseErrorConfig<MeListsItemAddEndpoint401>,
    ResponseConfig<MeListsItemAddEndpointQueryResponse>,
    typeof queryKey
  >({
    enabled: !!(listId && gameId),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meListsItemAddEndpointInfinite(listId, gameId, config)
    },
    initialPageParam: 1,
    getNextPageParam: (lastPage) => lastPage['pageNumber'],
    getPreviousPageParam: (firstPage) => firstPage['pageNumber'],
  })
}

/**
 * {@link /api/me/lists/add/:listId/:gameId}
 */
export function useMeListsItemAddEndpointInfinite<
  TData = InfiniteData<ResponseConfig<MeListsItemAddEndpointQueryResponse>>,
  TQueryData = ResponseConfig<MeListsItemAddEndpointQueryResponse>,
  TQueryKey extends QueryKey = MeListsItemAddEndpointInfiniteQueryKey,
>(
  listId: MeListsItemAddEndpointPathParams['listId'],
  gameId: MeListsItemAddEndpointPathParams['gameId'],
  options: {
    query?: Partial<
      InfiniteQueryObserverOptions<
        ResponseConfig<MeListsItemAddEndpointQueryResponse>,
        ResponseErrorConfig<MeListsItemAddEndpoint401>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meListsItemAddEndpointInfiniteQueryKey(listId, gameId)

  const query = useInfiniteQuery(
    {
      ...(meListsItemAddEndpointInfiniteQueryOptions(listId, gameId, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<MeListsItemAddEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}