// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shared.Features;
using Worker.Data;

#nullable disable

namespace Worker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250906210311_ChangeGameEntityIdGeneration")]
    partial class ChangeGameEntityIdGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Features.GameEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.PrimitiveCollection<long[]>("GameEngines")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("game_engines");

                    b.Property<long>("GameType")
                        .HasColumnType("bigint")
                        .HasColumnName("game_type");

                    b.PrimitiveCollection<long[]>("Genres")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("genres");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<long[]>("Platforms")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("platforms");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<double>("RatingCount")
                        .HasColumnType("double precision")
                        .HasColumnName("rating_count");

                    b.Property<IGDBGame>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<Instant>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.PrimitiveCollection<long[]>("Themes")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("themes");

                    b.Property<double>("TotalRating")
                        .HasColumnType("double precision")
                        .HasColumnName("total_rating");

                    b.Property<double>("TotalRatingCount")
                        .HasColumnType("double precision")
                        .HasColumnName("total_rating_count");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.ToTable("games", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
