// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shared.Features;
using Worker.Data;

#nullable disable

namespace Worker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Features.GameEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.PrimitiveCollection<long[]>("GameEngines")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("game_engines");

                    b.Property<long>("GameType")
                        .HasColumnType("bigint")
                        .HasColumnName("game_type");

                    b.PrimitiveCollection<long[]>("Genres")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("genres");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<long[]>("Platforms")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("platforms");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<long>("RatingCount")
                        .HasColumnType("bigint")
                        .HasColumnName("rating_count");

                    b.Property<IGDBGame>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<Instant>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.PrimitiveCollection<long[]>("Themes")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("themes");

                    b.Property<double>("TotalRating")
                        .HasColumnType("double precision")
                        .HasColumnName("total_rating");

                    b.Property<long>("TotalRatingCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_rating_count");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Shared.Features.Games.Franchise", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.PrimitiveCollection<List<long>>("Games")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("games")
                        .HasAnnotation("Relational:JsonPropertyName", "games");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_franchises");

                    b.ToTable("franchises", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "franchises");
                });

            modelBuilder.Entity("Shared.Features.Games.GameEngine", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<long>("LogoId")
                        .HasColumnType("bigint")
                        .HasColumnName("logo_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_game_engines");

                    b.HasIndex("LogoId")
                        .HasDatabaseName("ix_game_engines_logo_id");

                    b.ToTable("game_engines", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "game_engines");
                });

            modelBuilder.Entity("Shared.Features.Games.GameEngineLogo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_id")
                        .HasAnnotation("Relational:JsonPropertyName", "image_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_game_engine_logo");

                    b.ToTable("game_engine_logo", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "logo");
                });

            modelBuilder.Entity("Shared.Features.Games.GameMode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_game_modes");

                    b.ToTable("game_modes", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "game_modes");
                });

            modelBuilder.Entity("Shared.Features.Games.Genre", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "genres");
                });

            modelBuilder.Entity("Shared.Features.Games.Keyword", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_keywords");

                    b.ToTable("keywords", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "keywords");
                });

            modelBuilder.Entity("Shared.Features.Games.Platform", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation")
                        .HasAnnotation("Relational:JsonPropertyName", "abbreviation");

                    b.Property<long?>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation")
                        .HasAnnotation("Relational:JsonPropertyName", "generation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<long>("PlatformLogoId")
                        .HasColumnType("bigint")
                        .HasColumnName("platform_logo_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.HasKey("Id")
                        .HasName("pk_platforms");

                    b.HasIndex("PlatformLogoId")
                        .HasDatabaseName("ix_platforms_platform_logo_id");

                    b.ToTable("platforms", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "platforms");
                });

            modelBuilder.Entity("Shared.Features.Games.PlatformLogo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_id")
                        .HasAnnotation("Relational:JsonPropertyName", "image_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_platform_logo");

                    b.ToTable("platform_logo", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "platform_logo");
                });

            modelBuilder.Entity("Shared.Features.Games.PlayerPerspective", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_player_perspectives");

                    b.ToTable("player_perspectives", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "player_perspectives");
                });

            modelBuilder.Entity("Shared.Features.Games.Theme", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug")
                        .HasAnnotation("Relational:JsonPropertyName", "slug");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id")
                        .HasName("pk_themes");

                    b.ToTable("themes", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "themes");
                });

            modelBuilder.Entity("Shared.Features.Games.GameEngine", b =>
                {
                    b.HasOne("Shared.Features.Games.GameEngineLogo", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_engines_game_engine_logo_logo_id");

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("Shared.Features.Games.Platform", b =>
                {
                    b.HasOne("Shared.Features.Games.PlatformLogo", "PlatformLogo")
                        .WithMany()
                        .HasForeignKey("PlatformLogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_platforms_platform_logo_platform_logo_id");

                    b.Navigation("PlatformLogo");
                });
#pragma warning restore 612, 618
        }
    }
}
