// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PlayAPISDK.Catalog.Steam.ConcurrentUsers.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PlayAPISDK.Catalog.Steam.ConcurrentUsers
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\steam\concurrent-users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConcurrentUsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the PlayAPISDK.catalog.steam.concurrentUsers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.Item.WithGameItemRequestBuilder"/></returns>
        public global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.Item.WithGameItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("gameId", position);
                return new global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.Item.WithGameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the PlayAPISDK.catalog.steam.concurrentUsers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.Item.WithGameItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.Item.WithGameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("gameId", position);
                return new global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.Item.WithGameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.ConcurrentUsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConcurrentUsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/steam/concurrent-users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PlayAPISDK.Catalog.Steam.ConcurrentUsers.ConcurrentUsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConcurrentUsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/steam/concurrent-users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
