# the future, use enviroment variables

[destination.postgres.credentials]
database = "catalogdev"
password = "PQDF13*7dpR-Q77nmQZh*3"
username = "postgres"
host = "localhost"
port = 5433
connect_timeout = 15