// <auto-generated />
using Catalog.Data;
using IGDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_search");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Companies.Models.CompanyEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("ChangedCompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_company_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Company>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("ChangedCompanyId")
                        .HasDatabaseName("ix_companies_changed_company_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_companies_parent_id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Catalog.Franchises.Models.FranchiseEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Franchise>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_franchises");

                    b.ToTable("franchises", (string)null);
                });

            modelBuilder.Entity("Catalog.GameEngines.Models.GameEngineEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<GameEngineLogo>("Logo")
                        .HasColumnType("jsonb")
                        .HasColumnName("logo");

                    b.Property<GameEngine>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_game_engines");

                    b.ToTable("game_engines", (string)null);
                });

            modelBuilder.Entity("Catalog.GameModes.Models.GameModeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_game_modes");

                    b.ToTable("game_modes", (string)null);
                });

            modelBuilder.Entity("Catalog.Games.Models.GameEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("FirstReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_release_date");

                    b.Property<long?>("GameEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_entity_id");

                    b.Property<long>("GameType")
                        .HasColumnType("bigint")
                        .HasColumnName("game_type");

                    b.Property<Game>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<long?>("RatingCount")
                        .HasColumnType("bigint")
                        .HasColumnName("rating_count");

                    b.Property<double?>("TotalRating")
                        .HasColumnType("double precision")
                        .HasColumnName("total_rating");

                    b.Property<long?>("TotalRatingCount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_rating_count");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("GameEntityId")
                        .HasDatabaseName("ix_games_game_entity_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Catalog.Genres.Models.GenreEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Catalog.Platforms.Models.PlatformEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<PlatformLogo>("Logo")
                        .HasColumnType("jsonb")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_platforms");

                    b.ToTable("platforms", (string)null);
                });

            modelBuilder.Entity("Catalog.PlayerPerspective.Models.PlayerPerspectiveEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_player_perspectives");

                    b.ToTable("player_perspectives", (string)null);
                });

            modelBuilder.Entity("Catalog.Themes.Models.ThemeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_themes");

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("FranchiseEntityGameEntity", b =>
                {
                    b.Property<long>("FranchisesId")
                        .HasColumnType("bigint")
                        .HasColumnName("franchises_id");

                    b.Property<long>("GamesId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_id");

                    b.HasKey("FranchisesId", "GamesId")
                        .HasName("pk_franchise_entity_game_entity");

                    b.HasIndex("GamesId")
                        .HasDatabaseName("ix_franchise_entity_game_entity_games_id");

                    b.ToTable("franchise_entity_game_entity", (string)null);
                });

            modelBuilder.Entity("GameEngineEntityGameEntity", b =>
                {
                    b.Property<long>("GameEnginesId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_engines_id");

                    b.Property<long>("GamesId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_id");

                    b.HasKey("GameEnginesId", "GamesId")
                        .HasName("pk_game_engine_entity_game_entity");

                    b.HasIndex("GamesId")
                        .HasDatabaseName("ix_game_engine_entity_game_entity_games_id");

                    b.ToTable("game_engine_entity_game_entity", (string)null);
                });

            modelBuilder.Entity("GameEntityGameModeEntity", b =>
                {
                    b.Property<long>("GameModesId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_modes_id");

                    b.Property<long>("GamesId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_id");

                    b.HasKey("GameModesId", "GamesId")
                        .HasName("pk_game_entity_game_mode_entity");

                    b.HasIndex("GamesId")
                        .HasDatabaseName("ix_game_entity_game_mode_entity_games_id");

                    b.ToTable("game_entity_game_mode_entity", (string)null);
                });

            modelBuilder.Entity("GameEntityGenreEntity", b =>
                {
                    b.Property<long>("GamesId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_id");

                    b.Property<long>("GenresId")
                        .HasColumnType("bigint")
                        .HasColumnName("genres_id");

                    b.HasKey("GamesId", "GenresId")
                        .HasName("pk_game_entity_genre_entity");

                    b.HasIndex("GenresId")
                        .HasDatabaseName("ix_game_entity_genre_entity_genres_id");

                    b.ToTable("game_entity_genre_entity", (string)null);
                });

            modelBuilder.Entity("GameEntityPlatformEntity", b =>
                {
                    b.Property<long>("GamesId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_id");

                    b.Property<long>("PlatformsId")
                        .HasColumnType("bigint")
                        .HasColumnName("platforms_id");

                    b.HasKey("GamesId", "PlatformsId")
                        .HasName("pk_game_entity_platform_entity");

                    b.HasIndex("PlatformsId")
                        .HasDatabaseName("ix_game_entity_platform_entity_platforms_id");

                    b.ToTable("game_entity_platform_entity", (string)null);
                });

            modelBuilder.Entity("GameEntityPlayerPerspectiveEntity", b =>
                {
                    b.Property<long>("GamesId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_id");

                    b.Property<long>("PlayerPerspectivesId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_perspectives_id");

                    b.HasKey("GamesId", "PlayerPerspectivesId")
                        .HasName("pk_game_entity_player_perspective_entity");

                    b.HasIndex("PlayerPerspectivesId")
                        .HasDatabaseName("ix_game_entity_player_perspective_entity_player_perspectives_id");

                    b.ToTable("game_entity_player_perspective_entity", (string)null);
                });

            modelBuilder.Entity("GameEntityThemeEntity", b =>
                {
                    b.Property<long>("GamesId")
                        .HasColumnType("bigint")
                        .HasColumnName("games_id");

                    b.Property<long>("ThemesId")
                        .HasColumnType("bigint")
                        .HasColumnName("themes_id");

                    b.HasKey("GamesId", "ThemesId")
                        .HasName("pk_game_entity_theme_entity");

                    b.HasIndex("ThemesId")
                        .HasDatabaseName("ix_game_entity_theme_entity_themes_id");

                    b.ToTable("game_entity_theme_entity", (string)null);
                });

            modelBuilder.Entity("developer_game", b =>
                {
                    b.Property<long>("company_id")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<long>("game_id")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.HasKey("company_id", "game_id")
                        .HasName("pk_developer_game");

                    b.HasIndex("game_id")
                        .HasDatabaseName("ix_developer_game_game_id");

                    b.ToTable("developer_game", (string)null);
                });

            modelBuilder.Entity("publisher_game", b =>
                {
                    b.Property<long>("company_id")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<long>("game_id")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.HasKey("company_id", "game_id")
                        .HasName("pk_publisher_game");

                    b.HasIndex("game_id")
                        .HasDatabaseName("ix_publisher_game_game_id");

                    b.ToTable("publisher_game", (string)null);
                });

            modelBuilder.Entity("Catalog.Companies.Models.CompanyEntity", b =>
                {
                    b.HasOne("Catalog.Companies.Models.CompanyEntity", "ChangedCompany")
                        .WithMany()
                        .HasForeignKey("ChangedCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_companies_companies_changed_company_id");

                    b.HasOne("Catalog.Companies.Models.CompanyEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_companies_companies_parent_id");

                    b.Navigation("ChangedCompany");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Catalog.Games.Models.GameEntity", b =>
                {
                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany("SimilarGames")
                        .HasForeignKey("GameEntityId")
                        .HasConstraintName("fk_games_games_game_entity_id");
                });

            modelBuilder.Entity("FranchiseEntityGameEntity", b =>
                {
                    b.HasOne("Catalog.Franchises.Models.FranchiseEntity", null)
                        .WithMany()
                        .HasForeignKey("FranchisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_franchise_entity_game_entity_franchises_franchises_id");

                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_franchise_entity_game_entity_games_games_id");
                });

            modelBuilder.Entity("GameEngineEntityGameEntity", b =>
                {
                    b.HasOne("Catalog.GameEngines.Models.GameEngineEntity", null)
                        .WithMany()
                        .HasForeignKey("GameEnginesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_engine_entity_game_entity_game_engines_game_engines_id");

                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_engine_entity_game_entity_games_games_id");
                });

            modelBuilder.Entity("GameEntityGameModeEntity", b =>
                {
                    b.HasOne("Catalog.GameModes.Models.GameModeEntity", null)
                        .WithMany()
                        .HasForeignKey("GameModesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_game_mode_entity_game_modes_game_modes_id");

                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_game_mode_entity_games_games_id");
                });

            modelBuilder.Entity("GameEntityGenreEntity", b =>
                {
                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_genre_entity_games_games_id");

                    b.HasOne("Catalog.Genres.Models.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_genre_entity_genres_genres_id");
                });

            modelBuilder.Entity("GameEntityPlatformEntity", b =>
                {
                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_platform_entity_games_games_id");

                    b.HasOne("Catalog.Platforms.Models.PlatformEntity", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_platform_entity_platforms_platforms_id");
                });

            modelBuilder.Entity("GameEntityPlayerPerspectiveEntity", b =>
                {
                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_player_perspective_entity_games_games_id");

                    b.HasOne("Catalog.PlayerPerspective.Models.PlayerPerspectiveEntity", null)
                        .WithMany()
                        .HasForeignKey("PlayerPerspectivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_player_perspective_entity_player_perspectives_p");
                });

            modelBuilder.Entity("GameEntityThemeEntity", b =>
                {
                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_theme_entity_games_games_id");

                    b.HasOne("Catalog.Themes.Models.ThemeEntity", null)
                        .WithMany()
                        .HasForeignKey("ThemesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_entity_theme_entity_themes_themes_id");
                });

            modelBuilder.Entity("developer_game", b =>
                {
                    b.HasOne("Catalog.Companies.Models.CompanyEntity", null)
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_developer_game_companies_company_id");

                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_developer_game_games_game_id");
                });

            modelBuilder.Entity("publisher_game", b =>
                {
                    b.HasOne("Catalog.Companies.Models.CompanyEntity", null)
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publisher_game_companies_company_id");

                    b.HasOne("Catalog.Games.Models.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("game_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publisher_game_games_game_id");
                });

            modelBuilder.Entity("Catalog.Games.Models.GameEntity", b =>
                {
                    b.Navigation("SimilarGames");
                });
#pragma warning restore 612, 618
        }
    }
}
