// <auto-generated/>
#pragma warning disable CS0618
using CatalogAPISDK.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace CatalogAPISDK.Catalog.Games.ReleaseDateRange
{
    /// <summary>
    /// Builds and executes requests for operations under \catalog\games\release-date-range
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReleaseDateRangeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleaseDateRangeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/games/release-date-range?End={End}&Limit={Limit}&Start={Start}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleaseDateRangeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/catalog/games/release-date-range?End={End}&Limit={Limit}&Start={Start}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::CatalogAPISDK.Models.GetByReleaseDateRangeResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::CatalogAPISDK.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::CatalogAPISDK.Models.GetByReleaseDateRangeResponse?> GetAsync(Action<RequestConfiguration<global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder.ReleaseDateRangeRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::CatalogAPISDK.Models.GetByReleaseDateRangeResponse> GetAsync(Action<RequestConfiguration<global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder.ReleaseDateRangeRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::CatalogAPISDK.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::CatalogAPISDK.Models.GetByReleaseDateRangeResponse>(requestInfo, global::CatalogAPISDK.Models.GetByReleaseDateRangeResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder.ReleaseDateRangeRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder.ReleaseDateRangeRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class ReleaseDateRangeRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            public Date? End { get; set; }
            public int? Limit { get; set; }
            public Date? Start { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReleaseDateRangeRequestBuilderGetRequestConfiguration : RequestConfiguration<global::CatalogAPISDK.Catalog.Games.ReleaseDateRange.ReleaseDateRangeRequestBuilder.ReleaseDateRangeRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
