/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { MeWishlistsAddEndpointMutationResponse, MeWishlistsAddEndpointPathParams, MeWishlistsAddEndpoint401 } from '../../types/MeWishlistsAddEndpoint.ts'
import { useMutation } from '@tanstack/react-query'

export const meWishlistsAddEndpointMutationKey = () => [{ url: '/api/me/wishlist/add/{gameId}' }] as const

export type MeWishlistsAddEndpointMutationKey = ReturnType<typeof meWishlistsAddEndpointMutationKey>

/**
 * {@link /api/me/wishlist/add/:gameId}
 */
export async function meWishlistsAddEndpoint(
  gameId: MeWishlistsAddEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<MeWishlistsAddEndpointMutationResponse, ResponseErrorConfig<MeWishlistsAddEndpoint401>, unknown>({
    method: 'POST',
    url: `/api/me/wishlist/add/${gameId}`,
    ...requestConfig,
  })
  return res.data
}

/**
 * {@link /api/me/wishlist/add/:gameId}
 */
export function useMeWishlistsAddEndpoint<TContext>(
  options: {
    mutation?: UseMutationOptions<
      MeWishlistsAddEndpointMutationResponse,
      ResponseErrorConfig<MeWishlistsAddEndpoint401>,
      { gameId: MeWishlistsAddEndpointPathParams['gameId'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? meWishlistsAddEndpointMutationKey()

  return useMutation<
    MeWishlistsAddEndpointMutationResponse,
    ResponseErrorConfig<MeWishlistsAddEndpoint401>,
    { gameId: MeWishlistsAddEndpointPathParams['gameId'] },
    TContext
  >(
    {
      mutationFn: async ({ gameId }) => {
        return meWishlistsAddEndpoint(gameId, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}