/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type {
  MeListsItemRemoveEndpointQueryResponse,
  MeListsItemRemoveEndpointPathParams,
  MeListsItemRemoveEndpoint401,
} from '../../types/MeListsItemRemoveEndpoint.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const meListsItemRemoveEndpointSuspenseQueryKey = (
  listId: MeListsItemRemoveEndpointPathParams['listId'],
  gameId: MeListsItemRemoveEndpointPathParams['gameId'],
) => [{ url: '/api/me/lists/remove/:listId/:gameId', params: { listId: listId, gameId: gameId } }] as const

export type MeListsItemRemoveEndpointSuspenseQueryKey = ReturnType<typeof meListsItemRemoveEndpointSuspenseQueryKey>

/**
 * {@link /api/me/lists/remove/:listId/:gameId}
 */
export async function meListsItemRemoveEndpointSuspense(
  listId: MeListsItemRemoveEndpointPathParams['listId'],
  gameId: MeListsItemRemoveEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<MeListsItemRemoveEndpointQueryResponse, ResponseErrorConfig<MeListsItemRemoveEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/lists/remove/${listId}/${gameId}`,
    ...requestConfig,
  })
  return res.data
}

export function meListsItemRemoveEndpointSuspenseQueryOptions(
  listId: MeListsItemRemoveEndpointPathParams['listId'],
  gameId: MeListsItemRemoveEndpointPathParams['gameId'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = meListsItemRemoveEndpointSuspenseQueryKey(listId, gameId)
  return queryOptions<
    MeListsItemRemoveEndpointQueryResponse,
    ResponseErrorConfig<MeListsItemRemoveEndpoint401>,
    MeListsItemRemoveEndpointQueryResponse,
    typeof queryKey
  >({
    enabled: !!(listId && gameId),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meListsItemRemoveEndpointSuspense(listId, gameId, config)
    },
  })
}

/**
 * {@link /api/me/lists/remove/:listId/:gameId}
 */
export function useMeListsItemRemoveEndpointSuspense<
  TData = MeListsItemRemoveEndpointQueryResponse,
  TQueryKey extends QueryKey = MeListsItemRemoveEndpointSuspenseQueryKey,
>(
  listId: MeListsItemRemoveEndpointPathParams['listId'],
  gameId: MeListsItemRemoveEndpointPathParams['gameId'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<MeListsItemRemoveEndpointQueryResponse, ResponseErrorConfig<MeListsItemRemoveEndpoint401>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meListsItemRemoveEndpointSuspenseQueryKey(listId, gameId)

  const query = useSuspenseQuery(
    {
      ...meListsItemRemoveEndpointSuspenseQueryOptions(listId, gameId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<MeListsItemRemoveEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}