/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { MeProfileGetEndpointQueryResponse, MeProfileGetEndpoint401 } from '../../types/MeProfileGetEndpoint.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const meProfileGetEndpointQueryKey = () => [{ url: '/api/me/profile/me' }] as const

export type MeProfileGetEndpointQueryKey = ReturnType<typeof meProfileGetEndpointQueryKey>

/**
 * {@link /api/me/profile/me}
 */
export async function meProfileGetEndpoint(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<MeProfileGetEndpointQueryResponse, ResponseErrorConfig<MeProfileGetEndpoint401>, unknown>({
    method: 'GET',
    url: `/api/me/profile/me`,
    ...requestConfig,
  })
  return res.data
}

export function meProfileGetEndpointQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = meProfileGetEndpointQueryKey()
  return queryOptions<MeProfileGetEndpointQueryResponse, ResponseErrorConfig<MeProfileGetEndpoint401>, MeProfileGetEndpointQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return meProfileGetEndpoint(config)
    },
  })
}

/**
 * {@link /api/me/profile/me}
 */
export function useMeProfileGetEndpoint<
  TData = MeProfileGetEndpointQueryResponse,
  TQueryData = MeProfileGetEndpointQueryResponse,
  TQueryKey extends QueryKey = MeProfileGetEndpointQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<MeProfileGetEndpointQueryResponse, ResponseErrorConfig<MeProfileGetEndpoint401>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? meProfileGetEndpointQueryKey()

  const query = useQuery(
    {
      ...meProfileGetEndpointQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<MeProfileGetEndpoint401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}